---
title: "Parameter Table"
author: "Kaveh G. Siah"
date: "11/12/2020"
output: 
  pdf_document:
  geometry: margin=2 cm
  fig_caption: yes
  bibliography: Manuscript.bib
---


```{r}
library(kableExtra)

```

```{r, echo=FALSE}


Parameter<-c("Soil Layer", "Soil Layer", "Depth", "Thickness", "Bulk Density", "Solid Density", "Stoniness", "Root Fraction", "pKGibb", "pkAl precip", "pCO2", "Area", "Wilting Point", "Field Capacity", "Saturation", "CEC", "KH Cation", "Percent Mineral Area", "Uptake Fraction Per Layer (all nutrients)", "Nitrification (ks, knit)", "Microbial Turnover", "Organic Matter Parameters", "Soil Solution Initial (Multiple Species)", "Soil Adsorbed Anions Initial", "CEC Initial")


Source<-c("Calibrative", "Calibrative", "Calibrative", "Calibrative; ERS Lysimeter", "Hynicka et al., 2016", "N/A", "Hynicka et al., 2016", "Harrington et al., 2017","Calibrative; Anderson et al., 2002","Al precipitation constant (unused in current version)", "Original","Calibrative; Sverdrup and Warfvinge 1993","NCSS: Enter Site Details?", "NCSS", "Assumed", "Hynicka et al., 2016", "Calculated using ERS Lysimeter and Hynicka et al., 2016: Partial Calibration", "Calibrative: Anderson et al., 2002, NCSS, Franklin and Williams 1971" , "Poszwa et al., 2002", "Perakis and Sinkhorn, 2011; Calibrative", "Original", "Perakis and Sinkhorn, 2011", "ERS Lysimeter", "Needs to be checked; Harward et al., 1962 for Adsorption Dynamics; Chappell and Miller, 1988; Johnson and Lindburg 1992", "Hynicka et al., 2016")


text_tbl_2 <- data.frame(
Parameter, Source
)

kbl(text_tbl_2,"latex" ,booktabs = TRUE, col.names= c("Input Parameter", "Source"), escape=FALSE) %>% kable_styling(full_width = F, latex_options = c("scale_down", "striped", "hold_position"))%>% save_kable("Tables/Soilparam.pdf")

```

<br>

```{r, echo=FALSE, message=FALSE}

text_tbl_1 <- data.frame(
Parameter= c("Nutrient Deposition Fluxes", "Monthly Soil Temperature"),
Source = c("NADP, ALSEA Site", "FIND LINK")
)

kbl(text_tbl_1,"latex" ,booktabs = T, col.names =  c("Parameter","Source"), escape=FALSE) %>%
kable_styling(full_width = F, latex_options = c("scale_down", "hold_position", font_size=12)) %>% save_kable("Tables/Other.pdf")

```

<br>

```{r, echo=FALSE, message=FALSE}

Parameter_T3<-c("Litter Concentration (N, Ca, Mg,K, S, P)", "Litter C Pool", "Layer frac (Fine, Coarse, Humus)", "Decomp rate", "CO2FACT", "Nutrient Factor (DOCFACT, N Fact, Ca Fact, Mg Fact, K Fact, S Fact, P Fact")


Source_T3<-c("Perakis and Sinkhorn, 2011", "Perakis and Sinkhorn, 2011", "Grier and Cole 1977; Johnson et al., 1992", "Calibration", "Calibration ", "Calibration")

text_tbl_3 <- data.frame(
Parameter_T3, Source_T3
)

kbl(text_tbl_3,"latex" , booktabs=TRUE, col.names= c("Parameter", "Source"), escape=FALSE) %>% kable_styling(full_width = F, latex_options = c("scale_down", "striped", "HOLD_position"), font_size=12) %>%
  save_kable("Tables/Litter.pdf")


```

<br>

```{r, echo=FALSE, message=FALSE}

Parameter_T4<-c("Start Year", "End Year", "Nb Layers", "Nb Minerals", "Mineral names", "OA pka", "Aluminum", "Phosphoric Acid", "DIC", "Organic acid size", "Nb Tree comp*", "Anion Adsorption isotherms")

Units_T4<-c("Year", "Year", "N/A", "N/A", "N/A", "N/A", "N/A", "N/A","N/A", "Carbon/Charge", "N/A", "N/A")

Description_T4<-c("Perakis and Sinkhorn, 2011", "Calibration", "Calibration", "Franklin 1980; Anderson et al., 2002", "Franklin 1980, Anderson et al., 2002, NCRS samples. ", "Past Calibration", "Past Calibration", "Past Calibration", "Past Calibration", "Calibration", "Stand Assumption", "Calibration")

text_tbl_4 <- data.frame(
Parameter_T4, Units_T4, Description_T4
)

kbl(text_tbl_4,"latex", booktabs = TRUE, col.names= c("Input Parameter", "Units", "Source"), escape=FALSE) %>% kable_styling(full_width = F, latex_options = c("scale_down", "striped", "hold_position")) %>%
  save_kable("Tables/General.pdf")

```


```{r, echo=FALSE, message=FALSE}
Parameter_T6<-c("Foliage.start", "Foliage.End","PET.winter.factor","PET.summer.factor","interception" ,"AET.Reduc","Leaching.alpha","Absorption.alpha","Foliar.target.conc","Percent.variation, foliar","Translocation.Percent","Foliar.Exudation","Foliar.Leaching","Foliar.absorption","Wood.target.conc","Wood.initial.conc","Percent.variation, Wood","Bark.target.conc","Bark.initial.conc","Percent.variation, Bark","Branch.target.conc","Branch.initial.conc","Percent.variation, Branch")

Units_T6<-c("$g/m^2$", "$g/m^2$","Multiple","Multiple","cm" ,"Multiple","N/A","N/A","$\\mu$mol/g","Fraction","Fraction","N/A","N/A","N/A","$\\mu$mol/g","Percent.variation","$\\mu$mol/g","$\\mu$mol/g","Percent.variation","","$\\mu$mol/g","$\\mu$mol/g","Fraction")

Description_T6<-c("CIPSANON", "CIPSANON","Calibration","Calibration","Bixby 2000, Link et al., 2004, Rothacher 1963" ,"Multiplies by calculated AET to reduce or enhance AET.","Reaction order for foliar leaching reaction.","Reaction order for foliar adsoprtion reaction.","Determines foliar concentration of nutrients.","Fraction of target concentration which foliage can reach before limitation.","Fraction of foliar nutrients that are translocated to stem during litterfall events.","NULL","NULL","NULL","Wood.target.conc","Wood.initial.conc","Percent.variation, Wood","Bark.target.conc","Bark.initial.conc","Percent.variation, Bark","Branch.target.conc","Branch.initial.conc","Percent.variation, Branch")


text_tbl_6 <- data.frame(
Parameter_T6, Units_T6, Description_T6)

kbl(text_tbl_6,"latex" , booktabs = TRUE, col.names= c("Input Parameter", "Units", "Description"), escape=FALSE) %>% kable_styling(full_width = F, latex_options = c("scale_down", "striped", "HOLD_position")) %>%
  save_kable("Tables/TreeParam.pdf")

```


```{r}
Parameter_T7<-c("Year", "Month",	"Stand.Frac", "Wood.Exp.frac", "Bark.Exp.frac", "Branch.Exp.frac", "Foliage.Exp.frac")

Units_T7<-c("Year", "Month", "Fraction", "Fraction", "Fraction", "Fraction", "Fraction")

Description_T7<-c("Assumed based on scenario.", "Assumed based on scenario.", "Assumed.", "Assumed.", "Assumed.", "Assumed.", "Assumed.")


text_tbl_7 <- data.frame(
Parameter_T7, Units_T7, Description_T7)

kbl(text_tbl_7, "latex", booktabs = TRUE, col.names= c("Input Parameter", "Units", "Source"), escape=FALSE) %>% kable_styling(full_width = F, latex_options = c("scale_down", "striped", "HOLD_position")) %>%
  save_kable("Tables/StndHrvst.pdf")
```




