---
title: "CEC and AEC Figure Gen."
output:
  html_document:
    df_print: paged
---

```{r}
library(ggplot2)
library(dplyr)
library(multipanelfigure)

```

```{r}
# LN_SED Base Case\

# Update File

source("~/Project_Master/Test_Rep/Code/LN_SED/Base/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_SED/Base")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Calibration/Output_LN_SED/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)

```
```{r}
source("~/Project_Master/Test_Rep/Code/LN_SED/40_BO/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_SED/40_BO")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_SED/40_BO/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```

```{r}
source("~/Project_Master/Test_Rep/Code/LN_SED/40_WTH/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_SED/40_WTH")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_SED/40_WTH/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```

```{r}
source("~/Project_Master/Test_Rep/Code/LN_SED/80_BO/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_SED/80_BO")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_SED/80_BO/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```

```{r}
source("~/Project_Master/Test_Rep/Code/LN_SED/80_WTH/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_SED/80_WTH")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_SED/80_WTH/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```



```{r}
# LN_SED Base Case\

# Update File

source("~/Project_Master/Test_Rep/Code/HN_SED/Base/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_SED/Base")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Calibration/Output_HN_SED/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```





```{r}
source("~/Project_Master/Test_Rep/Code/LN_BAS/Base/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_BAS/Base")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Calibration/Output_LN_BAS/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```


```{r}
# HN_SED Base Case\

# Update File

source("~/Project_Master/Test_Rep/Code/HN_SED/Base/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_SED/Base")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Calibration/Output_HN_SED/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)

```
```{r}
source("~/Project_Master/Test_Rep/Code/HN_SED/40_BO/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_SED/40_BO")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_SED/40_BO/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```

```{r}
source("~/Project_Master/Test_Rep/Code/HN_SED/40_WTH/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_SED/40_WTH")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_SED/40_WTH/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```

```{r}
source("~/Project_Master/Test_Rep/Code/HN_SED/80_BO/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_SED/80_BO")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_SED/80_BO/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```

```{r}
source("~/Project_Master/Test_Rep/Code/HN_SED/80_WTH/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_SED/80_WTH")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_SED/80_WTH/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```



```{r}
# HN_SED Base Case\

# Update File

source("~/Project_Master/Test_Rep/Code/HN_SED/Base/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_SED/Base")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Calibration/Output_HN_SED/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```

```{r}
# HN_BAS Base Case\

# Update File

source("~/Project_Master/Test_Rep/Code/HN_BAS/Base/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_BAS/Base")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Calibration/Output_HN_BAS/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)

```
```{r}
source("~/Project_Master/Test_Rep/Code/HN_BAS/40_BO/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_BAS/40_BO")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_BAS/40_BO/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```

```{r}
source("~/Project_Master/Test_Rep/Code/HN_BAS/40_WTH/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_BAS/40_WTH")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_BAS/40_WTH/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```

```{r}
source("~/Project_Master/Test_Rep/Code/HN_BAS/80_BO/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_BAS/80_BO")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_BAS/80_BO/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```

```{r}
source("~/Project_Master/Test_Rep/Code/HN_BAS/80_WTH/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_BAS/80_WTH")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_BAS/80_WTH/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```



```{r}
# HN_BAS Base Case\

# Update File

source("~/Project_Master/Test_Rep/Code/HN_BAS/Base/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_BAS/Base")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Calibration/Output_HN_BAS/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```


```{r}
# LN_BAS Base Case\

# Update File

source("~/Project_Master/Test_Rep/Code/LN_BAS/Base/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_BAS/Base")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Calibration/Output_LN_BAS/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)

```
```{r}
source("~/Project_Master/Test_Rep/Code/LN_BAS/40_BO/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_BAS/40_BO")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_BAS/40_BO/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```

```{r}
source("~/Project_Master/Test_Rep/Code/LN_BAS/40_WTH/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_BAS/40_WTH")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_BAS/40_WTH/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```

```{r}
source("~/Project_Master/Test_Rep/Code/LN_BAS/80_BO/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_BAS/80_BO")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_BAS/80_BO/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```

```{r}
source("~/Project_Master/Test_Rep/Code/LN_BAS/80_WTH/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_BAS/80_WTH")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_BAS/80_WTH/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```



```{r}
# LN_BAS Base Case\

# Update File

source("~/Project_Master/Test_Rep/Code/LN_BAS/Base/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/Functions/Grapher_CEC_AEC.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_BAS/Base")

CEC_All<-read.csv2("~/Project_Master/Test_Rep/Output/Calibration/Output_LN_BAS/Edited Data/CEC_All.csv", header=TRUE)
CEC_All$group_id<-as.factor(CEC_All$group_id)

CEC_All$Date<-as.Date(CEC_All$Date)

CEC_Ca<-CEC_Grapher(CEC_All$Ca)
Ca<-CEC_Ca+labs(y="Ca on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Mg<-CEC_Grapher(CEC_All$Mg)
Mg<-CEC_Mg+labs(y="Mg on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_K<-CEC_Grapher(CEC_All$K)
K<-CEC_K+labs(y="K on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Na<-CEC_Grapher(CEC_All$Na)
Na<-CEC_Na+labs(y="Na on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_Al<-CEC_Grapher(CEC_All$Al)
Al<-CEC_Al+labs(y="Al on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

CEC_NH4<-CEC_Grapher(CEC_All$NH4)
NH4<-CEC_NH4+labs(y="NH4 on cation exchange surfaces (kg/ha)", color="Layer Number")+ scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+ scale_x_date(date_labels = "%Y")

figure1 <- multi_panel_figure(
  width = 1000, height = 350,
  columns = 3, rows = 2)

Fig1<-figure1 %>% fill_panel(Ca,column =1,row = 1) %>%
  fill_panel(Mg, column=2, row=1) %>%
  fill_panel(K, column=3, row=1) %>%
  fill_panel(Na, column=1, row=2) %>%
  fill_panel(Al, column=2, row=2) %>%
  fill_panel(NH4, column=3, row=2)

save_multi_panel_figure(Fig1, "CEC_All.png", limitsize=FALSE)
```

