---
title: "Concentration Figure Production"
output:
  html_document:
    df_print: paged
---

```{r}
library(ggplot2)
library(dplyr)
library(reshape2)
library(lubridate)
library(ggpubr)
library(gridExtra)
library(grid)
library(cowplot)
library(scales)
```

```{r}
source("~/Project_Master/Test_Rep/Code/LN_SED/40_BO/TreeNut_Mutator.R")


rm(list = ls())

setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_SED/40_BO")

Tree_Nut<-read.csv2("~/NutsForSEDLN/40_BO/Output data/Biomass/Tree data.csv", header=FALSE)

Tree_Nut_Fol<-Tree_Nut %>%
  select(V1:V15)

Tree_Nut_Fol2<-Tree_Nut_Fol %>% 
  rename("Year"=V1, "Fol_Biomass"=V3, "Month"=V2, "N_Conc"=V4, "Ca_Conc"=V5,
         "Mg_Conc"=V6, "K_Conc"=V7, "S_Conc"=V8, "P_Conc"=V9, "N_Content"=V10, "Ca_Content"=V11,
         "Mg_Content"=V12, "K_Content"=V13, "S_Content"=V14, "P_Content"=V15) 
  
Tree_Nut_Fol2[c(1:15)]<-lapply(Tree_Nut_Fol2[c(1:15)], as.numeric)

AnalysisTime<-na.omit(Tree_Nut_Fol2)

AnalysisTime<-AnalysisTime %>% mutate(Date=make_date(Year, Month))


Fol_Bio<-ggplot(AnalysisTime, aes(x=Date, y=Fol_Biomass))+geom_line()+labs(x="Date", y="Foliar Biomass (kg/ha)")+ theme_bw()+
  labs(title="Foliar Biomass")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



Ca_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Ca_Conc))+geom_line()+labs(x="Date", y=expression(Ca~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+
  labs(title="Ca Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))

N_Conc<-ggplot(AnalysisTime,aes(x=Date, y=N_Conc))+geom_line()+labs(x="Date", y=expression(N~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="N Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



P_Conc<-ggplot(AnalysisTime,aes(x=Date, y=P_Conc))+geom_line()+labs(x="Date", y=expression(P~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="P Foliar Concentration")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



S_Conc<-ggplot(AnalysisTime,aes(x=Date, y=S_Conc))+geom_line()+labs(x="Date", y=expression(S~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="S Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14),  text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


K_Conc<-ggplot(AnalysisTime,aes(x=Date, y=K_Conc))+geom_line()+labs(x="Date", y=expression(K~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+ labs(title="K Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



Mg_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Mg_Conc))+geom_line()+labs(x="Date", y=expression(Mg~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="Mg Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


windowsFonts(A = windowsFont("Times New Roman"))

ggarrange(Ca_Conc, Mg_Conc, K_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc1.png", height=1000, width=650, res=95)

ggarrange(N_Conc, P_Conc, S_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc2.png", height=1000, width=650, res=95)


ggarrange(Ca_Conc, Mg_Conc, K_Conc,N_Conc, P_Conc, S_Conc, labels=c("A", "B", "C", "D", "E", "F"),ncol = 2, nrow = 3) %>%
  ggexport(filename="Conc3.png", height=1000, width=800, res=95)
```


```{r}
# Set WD
rm(list = ls())


# Update Output
source("~/Project_Master/Test_Rep/Code/LN_BAS/40_BO/TreeNut_Mutator.R")

# Clear Working Directory



setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_BAS/40_BO")




Tree_Nut<-read.csv2("~/NutsForBASLN/40_BO/Output data/Biomass/Tree data.csv", header=FALSE)

Tree_Nut_Fol<-Tree_Nut %>%
  select(V1:V15)

Tree_Nut_Fol2<-Tree_Nut_Fol %>% 
  rename("Year"=V1, "Fol_Biomass"=V3, "Month"=V2, "N_Conc"=V4, "Ca_Conc"=V5,
         "Mg_Conc"=V6, "K_Conc"=V7, "S_Conc"=V8, "P_Conc"=V9, "N_Content"=V10, "Ca_Content"=V11,
         "Mg_Content"=V12, "K_Content"=V13, "S_Content"=V14, "P_Content"=V15) 

Tree_Nut_Fol2[c(1:15)]<-lapply(Tree_Nut_Fol2[c(1:15)], as.numeric)

AnalysisTime<-na.omit(Tree_Nut_Fol2)

AnalysisTime<-AnalysisTime %>% mutate(Date=make_date(Year, Month))



Fol_Bio<-ggplot(AnalysisTime, aes(x=Date, y=Fol_Biomass))+geom_line()+labs(x="Date", y="Foliar Biomass (kg/ha)")+ theme_bw()+
  labs(title="Foliar Biomass")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



Ca_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Ca_Conc))+geom_line()+labs(x="Date", y=expression(Ca~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+
  labs(title="Ca Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))

N_Conc<-ggplot(AnalysisTime,aes(x=Date, y=N_Conc))+geom_line()+labs(x="Date", y=expression(N~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="N Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



P_Conc<-ggplot(AnalysisTime,aes(x=Date, y=P_Conc))+geom_line()+labs(x="Date", y=expression(P~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="P Foliar Concentration")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



S_Conc<-ggplot(AnalysisTime,aes(x=Date, y=S_Conc))+geom_line()+labs(x="Date", y=expression(S~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="S Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14),  text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


K_Conc<-ggplot(AnalysisTime,aes(x=Date, y=K_Conc))+geom_line()+labs(x="Date", y=expression(K~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+ labs(title="K Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



Mg_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Mg_Conc))+geom_line()+labs(x="Date", y=expression(Mg~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="Mg Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


windowsFonts(A = windowsFont("Times New Roman"))

ggarrange(Ca_Conc, Mg_Conc, K_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc1.png", height=1000, width=650)

ggarrange(N_Conc, P_Conc, S_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc2.png", height=1000, width=650, res=95)
```

```{r}
# Set WD
rm(list = ls())


# Update Output
source("~/Project_Master/Test_Rep/Code/HN_BAS/40_BO/TreeNut_Mutator.R")

# Clear Working Directory



setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_BAS/40_BO")




Tree_Nut<-read.csv2("~/NutsForBASHN/40_BO/Output data/Biomass/Tree data.csv", header=FALSE)

Tree_Nut_Fol<-Tree_Nut %>%
  select(V1:V15)

Tree_Nut_Fol2<-Tree_Nut_Fol %>% 
  rename("Year"=V1, "Fol_Biomass"=V3, "Month"=V2, "N_Conc"=V4, "Ca_Conc"=V5,
         "Mg_Conc"=V6, "K_Conc"=V7, "S_Conc"=V8, "P_Conc"=V9, "N_Content"=V10, "Ca_Content"=V11,
         "Mg_Content"=V12, "K_Content"=V13, "S_Content"=V14, "P_Content"=V15) 

Tree_Nut_Fol2[c(1:15)]<-lapply(Tree_Nut_Fol2[c(1:15)], as.numeric)

AnalysisTime<-na.omit(Tree_Nut_Fol2)

AnalysisTime<-AnalysisTime %>% mutate(Date=make_date(Year, Month))



Fol_Bio<-ggplot(AnalysisTime, aes(x=Date, y=Fol_Biomass))+geom_line()+labs(x="Date", y="Foliar Biomass (kg/ha)")+ theme_bw()+
  labs(title="Foliar Biomass")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



Ca_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Ca_Conc))+geom_line()+labs(x="Date", y=expression(Ca~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+
  labs(title="Ca Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))

N_Conc<-ggplot(AnalysisTime,aes(x=Date, y=N_Conc))+geom_line()+labs(x="Date", y=expression(N~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="N Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



P_Conc<-ggplot(AnalysisTime,aes(x=Date, y=P_Conc))+geom_line()+labs(x="Date", y=expression(P~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="P Foliar Concentration")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



S_Conc<-ggplot(AnalysisTime,aes(x=Date, y=S_Conc))+geom_line()+labs(x="Date", y=expression(S~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="S Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14),  text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


K_Conc<-ggplot(AnalysisTime,aes(x=Date, y=K_Conc))+geom_line()+labs(x="Date", y=expression(K~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+ labs(title="K Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



Mg_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Mg_Conc))+geom_line()+labs(x="Date", y=expression(Mg~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="Mg Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


windowsFonts(A = windowsFont("Times New Roman"))

ggarrange(Ca_Conc, Mg_Conc, K_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc1.png", height=1000, width=650, res=95)

ggarrange(N_Conc, P_Conc, S_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc2.png", height=1000, width=650, res=95)


```

```{r}
# Set WD
rm(list = ls())


# Update Output
source("~/Project_Master/Test_Rep/Code/HN_SED/40_BO/TreeNut_Mutator.R")

# Clear Working Directory



setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_SED/40_BO")




Tree_Nut<-read.csv2("~/NutsForSEDHN/40_BO/Output data/Biomass/Tree data.csv", header=FALSE)

Tree_Nut_Fol<-Tree_Nut %>%
  select(V1:V15)

Tree_Nut_Fol2<-Tree_Nut_Fol %>% 
  rename("Year"=V1, "Fol_Biomass"=V3, "Month"=V2, "N_Conc"=V4, "Ca_Conc"=V5,
         "Mg_Conc"=V6, "K_Conc"=V7, "S_Conc"=V8, "P_Conc"=V9, "N_Content"=V10, "Ca_Content"=V11,
         "Mg_Content"=V12, "K_Content"=V13, "S_Content"=V14, "P_Content"=V15) 

Tree_Nut_Fol2[c(1:15)]<-lapply(Tree_Nut_Fol2[c(1:15)], as.numeric)

AnalysisTime<-na.omit(Tree_Nut_Fol2)

AnalysisTime<-AnalysisTime %>% mutate(Date=make_date(Year, Month))



Fol_Bio<-ggplot(AnalysisTime, aes(x=Date, y=Fol_Biomass))+geom_line()+labs(x="Date", y="Foliar Biomass (kg/ha)")+ theme_bw()+
  labs(title="Foliar Biomass")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



Ca_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Ca_Conc))+geom_line()+labs(x="Date", y=expression(Ca~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+
  labs(title="Ca Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))

N_Conc<-ggplot(AnalysisTime,aes(x=Date, y=N_Conc))+geom_line()+labs(x="Date", y=expression(N~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="N Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



P_Conc<-ggplot(AnalysisTime,aes(x=Date, y=P_Conc))+geom_line()+labs(x="Date", y=expression(P~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="P Foliar Concentration")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



S_Conc<-ggplot(AnalysisTime,aes(x=Date, y=S_Conc))+geom_line()+labs(x="Date", y=expression(S~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="S Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14),  text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


K_Conc<-ggplot(AnalysisTime,aes(x=Date, y=K_Conc))+geom_line()+labs(x="Date", y=expression(K~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+ labs(title="K Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



Mg_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Mg_Conc))+geom_line()+labs(x="Date", y=expression(Mg~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="Mg Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


windowsFonts(A = windowsFont("Times New Roman"))

ggarrange(Ca_Conc, Mg_Conc, K_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc1.png", height=1000, width=650, res=95)

ggarrange(N_Conc, P_Conc, S_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc2.png", height=1000, width=650, res=95)
```


```{r}
source("~/Project_Master/Test_Rep/Code/LN_SED/80_BO/TreeNut_Mutator.R")


rm(list = ls())

setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_SED/80_BO")

Tree_Nut<-read.csv2("~/NutsForSEDLN/80_BO/Output data/Biomass/Tree data.csv", header=FALSE)

Tree_Nut_Fol<-Tree_Nut %>%
  select(V1:V15)

Tree_Nut_Fol2<-Tree_Nut_Fol %>% 
  rename("Year"=V1, "Fol_Biomass"=V3, "Month"=V2, "N_Conc"=V4, "Ca_Conc"=V5,
         "Mg_Conc"=V6, "K_Conc"=V7, "S_Conc"=V8, "P_Conc"=V9, "N_Content"=V10, "Ca_Content"=V11,
         "Mg_Content"=V12, "K_Content"=V13, "S_Content"=V14, "P_Content"=V15) 
  
Tree_Nut_Fol2[c(1:15)]<-lapply(Tree_Nut_Fol2[c(1:15)], as.numeric)

AnalysisTime<-na.omit(Tree_Nut_Fol2)

AnalysisTime<-AnalysisTime %>% mutate(Date=make_date(Year, Month))



Fol_Bio<-ggplot(AnalysisTime, aes(x=Date, y=Fol_Biomass))+geom_line()+labs(x="Date", y="Foliar Biomass (kg/ha)")+ theme_bw()+
  labs(title="Foliar Biomass")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



Ca_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Ca_Conc))+geom_line()+labs(x="Date", y=expression(Ca~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+
  labs(title="Ca Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))

N_Conc<-ggplot(AnalysisTime,aes(x=Date, y=N_Conc))+geom_line()+labs(x="Date", y=expression(N~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="N Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



P_Conc<-ggplot(AnalysisTime,aes(x=Date, y=P_Conc))+geom_line()+labs(x="Date", y=expression(P~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="P Foliar Concentration")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



S_Conc<-ggplot(AnalysisTime,aes(x=Date, y=S_Conc))+geom_line()+labs(x="Date", y=expression(S~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="S Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14),  text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


K_Conc<-ggplot(AnalysisTime,aes(x=Date, y=K_Conc))+geom_line()+labs(x="Date", y=expression(K~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+ labs(title="K Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



Mg_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Mg_Conc))+geom_line()+labs(x="Date", y=expression(Mg~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="Mg Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


windowsFonts(A = windowsFont("Times New Roman"))

ggarrange(Ca_Conc, Mg_Conc, K_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc1.png", height=1000, width=650, res=95)

ggarrange(N_Conc, P_Conc, S_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc2.png", height=1000, width=650, res=95)

```


```{r}
source("~/Project_Master/Test_Rep/Code/LN_BAS/80_BO/TreeNut_Mutator.R")


rm(list = ls())

setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_BAS/80_BO")

Tree_Nut<-read.csv2("~/NutsForBASLN/80_BO/Output data/Biomass/Tree data.csv", header=FALSE)

Tree_Nut_Fol<-Tree_Nut %>%
  select(V1:V15)

Tree_Nut_Fol2<-Tree_Nut_Fol %>% 
  rename("Year"=V1, "Fol_Biomass"=V3, "Month"=V2, "N_Conc"=V4, "Ca_Conc"=V5,
         "Mg_Conc"=V6, "K_Conc"=V7, "S_Conc"=V8, "P_Conc"=V9, "N_Content"=V10, "Ca_Content"=V11,
         "Mg_Content"=V12, "K_Content"=V13, "S_Content"=V14, "P_Content"=V15) 
  
Tree_Nut_Fol2[c(1:15)]<-lapply(Tree_Nut_Fol2[c(1:15)], as.numeric)

AnalysisTime<-na.omit(Tree_Nut_Fol2)

AnalysisTime<-AnalysisTime %>% mutate(Date=make_date(Year, Month))



Fol_Bio<-ggplot(AnalysisTime, aes(x=Date, y=Fol_Biomass))+geom_line()+labs(x="Date", y="Foliar Biomass (kg/ha)")+ theme_bw()+
  labs(title="Foliar Biomass")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



Ca_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Ca_Conc))+geom_line()+labs(x="Date", y=expression(Ca~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+
  labs(title="Ca Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))

N_Conc<-ggplot(AnalysisTime,aes(x=Date, y=N_Conc))+geom_line()+labs(x="Date", y=expression(N~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="N Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



P_Conc<-ggplot(AnalysisTime,aes(x=Date, y=P_Conc))+geom_line()+labs(x="Date", y=expression(P~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="P Foliar Concentration")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



S_Conc<-ggplot(AnalysisTime,aes(x=Date, y=S_Conc))+geom_line()+labs(x="Date", y=expression(S~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="S Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14),  text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


K_Conc<-ggplot(AnalysisTime,aes(x=Date, y=K_Conc))+geom_line()+labs(x="Date", y=expression(K~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+ labs(title="K Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



Mg_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Mg_Conc))+geom_line()+labs(x="Date", y=expression(Mg~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="Mg Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


windowsFonts(A = windowsFont("Times New Roman"))

ggarrange(Ca_Conc, Mg_Conc, K_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc1.png", height=1000, width=650, res=95)

ggarrange(N_Conc, P_Conc, S_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc2.png", height=1000, width=650, res=95)
```

```{r}
source("~/Project_Master/Test_Rep/Code/HN_SED/80_BO/TreeNut_Mutator.R")


rm(list = ls())

setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_SED/80_BO")

Tree_Nut<-read.csv2("~/NutsForSEDHN/80_BO/Output data/Biomass/Tree data.csv", header=FALSE)

Tree_Nut_Fol<-Tree_Nut %>%
  select(V1:V15)

Tree_Nut_Fol2<-Tree_Nut_Fol %>% 
  rename("Year"=V1, "Fol_Biomass"=V3, "Month"=V2, "N_Conc"=V4, "Ca_Conc"=V5,
         "Mg_Conc"=V6, "K_Conc"=V7, "S_Conc"=V8, "P_Conc"=V9, "N_Content"=V10, "Ca_Content"=V11,
         "Mg_Content"=V12, "K_Content"=V13, "S_Content"=V14, "P_Content"=V15) 
  
Tree_Nut_Fol2[c(1:15)]<-lapply(Tree_Nut_Fol2[c(1:15)], as.numeric)

AnalysisTime<-na.omit(Tree_Nut_Fol2)

AnalysisTime<-AnalysisTime %>% mutate(Date=make_date(Year, Month))



Fol_Bio<-ggplot(AnalysisTime, aes(x=Date, y=Fol_Biomass))+geom_line()+labs(x="Date", y="Foliar Biomass (kg/ha)")+ theme_bw()+
  labs(title="Foliar Biomass")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



Ca_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Ca_Conc))+geom_line()+labs(x="Date", y=expression(Ca~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+
  labs(title="Ca Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))

N_Conc<-ggplot(AnalysisTime,aes(x=Date, y=N_Conc))+geom_line()+labs(x="Date", y=expression(N~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="N Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



P_Conc<-ggplot(AnalysisTime,aes(x=Date, y=P_Conc))+geom_line()+labs(x="Date", y=expression(P~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="P Foliar Concentration")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



S_Conc<-ggplot(AnalysisTime,aes(x=Date, y=S_Conc))+geom_line()+labs(x="Date", y=expression(S~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="S Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14),  text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


K_Conc<-ggplot(AnalysisTime,aes(x=Date, y=K_Conc))+geom_line()+labs(x="Date", y=expression(K~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+ labs(title="K Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



Mg_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Mg_Conc))+geom_line()+labs(x="Date", y=expression(Mg~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="Mg Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


windowsFonts(A = windowsFont("Times New Roman"))

ggarrange(Ca_Conc, Mg_Conc, K_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc1.png", height=1000, width=650, res=95)

ggarrange(N_Conc, P_Conc, S_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc2.png", height=1000, width=650, res=95)

```


```{r}
source("~/Project_Master/Test_Rep/Code/HN_BAS/80_BO/TreeNut_Mutator.R")


rm(list = ls())

setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_BAS/80_BO")

Tree_Nut<-read.csv2("~/NutsForBASHN/80_BO/Output data/Biomass/Tree data.csv", header=FALSE)

Tree_Nut_Fol<-Tree_Nut %>%
  select(V1:V15)

Tree_Nut_Fol2<-Tree_Nut_Fol %>% 
  rename("Year"=V1, "Fol_Biomass"=V3, "Month"=V2, "N_Conc"=V4, "Ca_Conc"=V5,
         "Mg_Conc"=V6, "K_Conc"=V7, "S_Conc"=V8, "P_Conc"=V9, "N_Content"=V10, "Ca_Content"=V11,
         "Mg_Content"=V12, "K_Content"=V13, "S_Content"=V14, "P_Content"=V15) 
  
Tree_Nut_Fol2[c(1:15)]<-lapply(Tree_Nut_Fol2[c(1:15)], as.numeric)

AnalysisTime<-na.omit(Tree_Nut_Fol2)

AnalysisTime<-AnalysisTime %>% mutate(Date=make_date(Year, Month))


Fol_Bio<-ggplot(AnalysisTime, aes(x=Date, y=Fol_Biomass))+geom_line()+labs(x="Date", y="Foliar Biomass (kg/ha)")+ theme_bw()+
  labs(title="Foliar Biomass")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



Ca_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Ca_Conc))+geom_line()+labs(x="Date", y=expression(Ca~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+
  labs(title="Ca Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))

N_Conc<-ggplot(AnalysisTime,aes(x=Date, y=N_Conc))+geom_line()+labs(x="Date", y=expression(N~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="N Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



P_Conc<-ggplot(AnalysisTime,aes(x=Date, y=P_Conc))+geom_line()+labs(x="Date", y=expression(P~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="P Foliar Concentration")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



S_Conc<-ggplot(AnalysisTime,aes(x=Date, y=S_Conc))+geom_line()+labs(x="Date", y=expression(S~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="S Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14),  text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


K_Conc<-ggplot(AnalysisTime,aes(x=Date, y=K_Conc))+geom_line()+labs(x="Date", y=expression(K~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+ labs(title="K Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



Mg_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Mg_Conc))+geom_line()+labs(x="Date", y=expression(Mg~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="Mg Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


windowsFonts(A = windowsFont("Times New Roman"))

ggarrange(Ca_Conc, Mg_Conc, K_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc1.png", height=1000, width=650, res=95)

ggarrange(N_Conc, P_Conc, S_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc2.png", height=1000, width=650, res=95)

```


```{r}
source("~/Project_Master/Test_Rep/Code/LN_BAS/80_WTH/TreeNut_Mutator.R")


rm(list = ls())

setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_BAS/80_WTH")

Tree_Nut<-read.csv2("~/NutsForBASLN/80_WTH/Output data/Biomass/Tree data.csv", header=FALSE)

Tree_Nut_Fol<-Tree_Nut %>%
  select(V1:V15)

Tree_Nut_Fol2<-Tree_Nut_Fol %>% 
  rename("Year"=V1, "Fol_Biomass"=V3, "Month"=V2, "N_Conc"=V4, "Ca_Conc"=V5,
         "Mg_Conc"=V6, "K_Conc"=V7, "S_Conc"=V8, "P_Conc"=V9, "N_Content"=V10, "Ca_Content"=V11,
         "Mg_Content"=V12, "K_Content"=V13, "S_Content"=V14, "P_Content"=V15) 
  
Tree_Nut_Fol2[c(1:15)]<-lapply(Tree_Nut_Fol2[c(1:15)], as.numeric)

AnalysisTime<-na.omit(Tree_Nut_Fol2)

AnalysisTime<-AnalysisTime %>% mutate(Date=make_date(Year, Month))



Fol_Bio<-ggplot(AnalysisTime, aes(x=Date, y=Fol_Biomass))+geom_line()+labs(x="Date", y="Foliar Biomass (kg/ha)")+ theme_bw()+
  labs(title="Foliar Biomass")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



Ca_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Ca_Conc))+geom_line()+labs(x="Date", y=expression(Ca~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+
  labs(title="Ca Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))

N_Conc<-ggplot(AnalysisTime,aes(x=Date, y=N_Conc))+geom_line()+labs(x="Date", y=expression(N~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="N Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



P_Conc<-ggplot(AnalysisTime,aes(x=Date, y=P_Conc))+geom_line()+labs(x="Date", y=expression(P~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="P Foliar Concentration")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



S_Conc<-ggplot(AnalysisTime,aes(x=Date, y=S_Conc))+geom_line()+labs(x="Date", y=expression(S~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="S Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14),  text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


K_Conc<-ggplot(AnalysisTime,aes(x=Date, y=K_Conc))+geom_line()+labs(x="Date", y=expression(K~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+ labs(title="K Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



Mg_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Mg_Conc))+geom_line()+labs(x="Date", y=expression(Mg~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="Mg Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


windowsFonts(A = windowsFont("Times New Roman"))

ggarrange(Ca_Conc, Mg_Conc, K_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc1.png", height=1000, width=650, res=95)

ggarrange(N_Conc, P_Conc, S_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc2.png", height=1000, width=650, res=95)
```

```{r}
source("~/Project_Master/Test_Rep/Code/HN_BAS/80_WTH/TreeNut_Mutator.R")


rm(list = ls())

setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_BAS/80_WTH")

Tree_Nut<-read.csv2("~/NutsForBASHN/80_WTH/Output data/Biomass/Tree data.csv", header=FALSE)

Tree_Nut_Fol<-Tree_Nut %>%
  select(V1:V15)

Tree_Nut_Fol2<-Tree_Nut_Fol %>% 
  rename("Year"=V1, "Fol_Biomass"=V3, "Month"=V2, "N_Conc"=V4, "Ca_Conc"=V5,
         "Mg_Conc"=V6, "K_Conc"=V7, "S_Conc"=V8, "P_Conc"=V9, "N_Content"=V10, "Ca_Content"=V11,
         "Mg_Content"=V12, "K_Content"=V13, "S_Content"=V14, "P_Content"=V15) 
  
Tree_Nut_Fol2[c(1:15)]<-lapply(Tree_Nut_Fol2[c(1:15)], as.numeric)

AnalysisTime<-na.omit(Tree_Nut_Fol2)

AnalysisTime<-AnalysisTime %>% mutate(Date=make_date(Year, Month))



Fol_Bio<-ggplot(AnalysisTime, aes(x=Date, y=Fol_Biomass))+geom_line()+labs(x="Date", y="Foliar Biomass (kg/ha)")+ theme_bw()+
  labs(title="Foliar Biomass")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



Ca_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Ca_Conc))+geom_line()+labs(x="Date", y=expression(Ca~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+
  labs(title="Ca Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))

N_Conc<-ggplot(AnalysisTime,aes(x=Date, y=N_Conc))+geom_line()+labs(x="Date", y=expression(N~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="N Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



P_Conc<-ggplot(AnalysisTime,aes(x=Date, y=P_Conc))+geom_line()+labs(x="Date", y=expression(P~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="P Foliar Concentration")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



S_Conc<-ggplot(AnalysisTime,aes(x=Date, y=S_Conc))+geom_line()+labs(x="Date", y=expression(S~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="S Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14),  text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


K_Conc<-ggplot(AnalysisTime,aes(x=Date, y=K_Conc))+geom_line()+labs(x="Date", y=expression(K~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+ labs(title="K Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



Mg_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Mg_Conc))+geom_line()+labs(x="Date", y=expression(Mg~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="Mg Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


windowsFonts(A = windowsFont("Times New Roman"))

ggarrange(Ca_Conc, Mg_Conc, K_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc1.png", height=1000, width=650, res=95)

ggarrange(N_Conc, P_Conc, S_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc2.png", height=1000, width=650, res=95)
```

```{r}
source("~/Project_Master/Test_Rep/Code/LN_SED/80_WTH/TreeNut_Mutator.R")


rm(list = ls())

setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_SED/80_WTH")

Tree_Nut<-read.csv2("~/NutsForSEDLN/80_WTH/Output data/Biomass/Tree data.csv", header=FALSE)

Tree_Nut_Fol<-Tree_Nut %>%
  select(V1:V15)

Tree_Nut_Fol2<-Tree_Nut_Fol %>% 
  rename("Year"=V1, "Fol_Biomass"=V3, "Month"=V2, "N_Conc"=V4, "Ca_Conc"=V5,
         "Mg_Conc"=V6, "K_Conc"=V7, "S_Conc"=V8, "P_Conc"=V9, "N_Content"=V10, "Ca_Content"=V11,
         "Mg_Content"=V12, "K_Content"=V13, "S_Content"=V14, "P_Content"=V15) 
  
Tree_Nut_Fol2[c(1:15)]<-lapply(Tree_Nut_Fol2[c(1:15)], as.numeric)

AnalysisTime<-na.omit(Tree_Nut_Fol2)

AnalysisTime<-AnalysisTime %>% mutate(Date=make_date(Year, Month))



Fol_Bio<-ggplot(AnalysisTime, aes(x=Date, y=Fol_Biomass))+geom_line()+labs(x="Date", y="Foliar Biomass (kg/ha)")+ theme_bw()+
  labs(title="Foliar Biomass")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



Ca_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Ca_Conc))+geom_line()+labs(x="Date", y=expression(Ca~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+
  labs(title="Ca Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))

N_Conc<-ggplot(AnalysisTime,aes(x=Date, y=N_Conc))+geom_line()+labs(x="Date", y=expression(N~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="N Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



P_Conc<-ggplot(AnalysisTime,aes(x=Date, y=P_Conc))+geom_line()+labs(x="Date", y=expression(P~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="P Foliar Concentration")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



S_Conc<-ggplot(AnalysisTime,aes(x=Date, y=S_Conc))+geom_line()+labs(x="Date", y=expression(S~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="S Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14),  text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


K_Conc<-ggplot(AnalysisTime,aes(x=Date, y=K_Conc))+geom_line()+labs(x="Date", y=expression(K~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+ labs(title="K Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



Mg_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Mg_Conc))+geom_line()+labs(x="Date", y=expression(Mg~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="Mg Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


windowsFonts(A = windowsFont("Times New Roman"))

ggarrange(Ca_Conc, Mg_Conc, K_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc1.png", height=1000, width=650, res=95)

ggarrange(N_Conc, P_Conc, S_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc2.png", height=1000, width=650, res=95)
```


```{r}
source("~/Project_Master/Test_Rep/Code/HN_SED/80_WTH/TreeNut_Mutator.R")


rm(list = ls())

setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_SED/80_WTH")

Tree_Nut<-read.csv2("~/NutsForSEDHN/80_WTH/Output data/Biomass/Tree data.csv", header=FALSE)

Tree_Nut_Fol<-Tree_Nut %>%
  select(V1:V15)

Tree_Nut_Fol2<-Tree_Nut_Fol %>% 
  rename("Year"=V1, "Fol_Biomass"=V3, "Month"=V2, "N_Conc"=V4, "Ca_Conc"=V5,
         "Mg_Conc"=V6, "K_Conc"=V7, "S_Conc"=V8, "P_Conc"=V9, "N_Content"=V10, "Ca_Content"=V11,
         "Mg_Content"=V12, "K_Content"=V13, "S_Content"=V14, "P_Content"=V15) 
  
Tree_Nut_Fol2[c(1:15)]<-lapply(Tree_Nut_Fol2[c(1:15)], as.numeric)

AnalysisTime<-na.omit(Tree_Nut_Fol2)

AnalysisTime<-AnalysisTime %>% mutate(Date=make_date(Year, Month))



Fol_Bio<-ggplot(AnalysisTime, aes(x=Date, y=Fol_Biomass))+geom_line()+labs(x="Date", y="Foliar Biomass (kg/ha)")+ theme_bw()+
  labs(title="Foliar Biomass")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



Ca_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Ca_Conc))+geom_line()+labs(x="Date", y=expression(Ca~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+
  labs(title="Ca Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))

N_Conc<-ggplot(AnalysisTime,aes(x=Date, y=N_Conc))+geom_line()+labs(x="Date", y=expression(N~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="N Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



P_Conc<-ggplot(AnalysisTime,aes(x=Date, y=P_Conc))+geom_line()+labs(x="Date", y=expression(P~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="P Foliar Concentration")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



S_Conc<-ggplot(AnalysisTime,aes(x=Date, y=S_Conc))+geom_line()+labs(x="Date", y=expression(S~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="S Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14),  text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


K_Conc<-ggplot(AnalysisTime,aes(x=Date, y=K_Conc))+geom_line()+labs(x="Date", y=expression(K~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+ labs(title="K Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



Mg_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Mg_Conc))+geom_line()+labs(x="Date", y=expression(Mg~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="Mg Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


windowsFonts(A = windowsFont("Times New Roman"))

ggarrange(Ca_Conc, Mg_Conc, K_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc1.png", height=1000, width=650, res=95)

ggarrange(N_Conc, P_Conc, S_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc2.png", height=1000, width=650, res=95)
```



```{r}
source("~/Project_Master/Test_Rep/Code/LN_BAS/40_WTH/TreeNut_Mutator.R")


rm(list = ls())

setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_BAS/40_WTH")

Tree_Nut<-read.csv2("~/NutsForBASLN/40_WTH/Output data/Biomass/Tree data.csv", header=FALSE)

Tree_Nut_Fol<-Tree_Nut %>%
  select(V1:V15)

Tree_Nut_Fol2<-Tree_Nut_Fol %>% 
  rename("Year"=V1, "Fol_Biomass"=V3, "Month"=V2, "N_Conc"=V4, "Ca_Conc"=V5,
         "Mg_Conc"=V6, "K_Conc"=V7, "S_Conc"=V8, "P_Conc"=V9, "N_Content"=V10, "Ca_Content"=V11,
         "Mg_Content"=V12, "K_Content"=V13, "S_Content"=V14, "P_Content"=V15) 
  
Tree_Nut_Fol2[c(1:15)]<-lapply(Tree_Nut_Fol2[c(1:15)], as.numeric)

AnalysisTime<-na.omit(Tree_Nut_Fol2)

AnalysisTime<-AnalysisTime %>% mutate(Date=make_date(Year, Month))



Fol_Bio<-ggplot(AnalysisTime, aes(x=Date, y=Fol_Biomass))+geom_line()+labs(x="Date", y="Foliar Biomass (kg/ha)")+ theme_bw()+
  labs(title="Foliar Biomass")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



Ca_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Ca_Conc))+geom_line()+labs(x="Date", y=expression(Ca~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+
  labs(title="Ca Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))

N_Conc<-ggplot(AnalysisTime,aes(x=Date, y=N_Conc))+geom_line()+labs(x="Date", y=expression(N~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="N Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



P_Conc<-ggplot(AnalysisTime,aes(x=Date, y=P_Conc))+geom_line()+labs(x="Date", y=expression(P~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="P Foliar Concentration")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



S_Conc<-ggplot(AnalysisTime,aes(x=Date, y=S_Conc))+geom_line()+labs(x="Date", y=expression(S~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="S Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14),  text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


K_Conc<-ggplot(AnalysisTime,aes(x=Date, y=K_Conc))+geom_line()+labs(x="Date", y=expression(K~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+ labs(title="K Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



Mg_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Mg_Conc))+geom_line()+labs(x="Date", y=expression(Mg~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="Mg Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


windowsFonts(A = windowsFont("Times New Roman"))

ggarrange(Ca_Conc, Mg_Conc, K_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc1.png", height=1000, width=650, res=95)

ggarrange(N_Conc, P_Conc, S_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc2.png", height=1000, width=650, res=95)
```

```{r}
source("~/Project_Master/Test_Rep/Code/HN_BAS/40_WTH/TreeNut_Mutator.R")


rm(list = ls())

setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_BAS/40_WTH")

Tree_Nut<-read.csv2("~/NutsForBASHN/40_WTH/Output data/Biomass/Tree data.csv", header=FALSE)

Tree_Nut_Fol<-Tree_Nut %>%
  select(V1:V15)

Tree_Nut_Fol2<-Tree_Nut_Fol %>% 
  rename("Year"=V1, "Fol_Biomass"=V3, "Month"=V2, "N_Conc"=V4, "Ca_Conc"=V5,
         "Mg_Conc"=V6, "K_Conc"=V7, "S_Conc"=V8, "P_Conc"=V9, "N_Content"=V10, "Ca_Content"=V11,
         "Mg_Content"=V12, "K_Content"=V13, "S_Content"=V14, "P_Content"=V15) 
  
Tree_Nut_Fol2[c(1:15)]<-lapply(Tree_Nut_Fol2[c(1:15)], as.numeric)

AnalysisTime<-na.omit(Tree_Nut_Fol2)

AnalysisTime<-AnalysisTime %>% mutate(Date=make_date(Year, Month))



Fol_Bio<-ggplot(AnalysisTime, aes(x=Date, y=Fol_Biomass))+geom_line()+labs(x="Date", y="Foliar Biomass (kg/ha)")+ theme_bw()+
  labs(title="Foliar Biomass")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



Ca_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Ca_Conc))+geom_line()+labs(x="Date", y=expression(Ca~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+
  labs(title="Ca Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))

N_Conc<-ggplot(AnalysisTime,aes(x=Date, y=N_Conc))+geom_line()+labs(x="Date", y=expression(N~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="N Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



P_Conc<-ggplot(AnalysisTime,aes(x=Date, y=P_Conc))+geom_line()+labs(x="Date", y=expression(P~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="P Foliar Concentration")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



S_Conc<-ggplot(AnalysisTime,aes(x=Date, y=S_Conc))+geom_line()+labs(x="Date", y=expression(S~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="S Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14),  text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


K_Conc<-ggplot(AnalysisTime,aes(x=Date, y=K_Conc))+geom_line()+labs(x="Date", y=expression(K~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+ labs(title="K Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



Mg_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Mg_Conc))+geom_line()+labs(x="Date", y=expression(Mg~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="Mg Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


windowsFonts(A = windowsFont("Times New Roman"))

ggarrange(Ca_Conc, Mg_Conc, K_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc1.png", height=1000, width=650, res=95)

ggarrange(N_Conc, P_Conc, S_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc2.png", height=1000, width=650, res=95)
```

```{r}
source("~/Project_Master/Test_Rep/Code/LN_SED/40_WTH/TreeNut_Mutator.R")


rm(list = ls())

setwd("~/Project_Master/Test_Rep/Manuscript/Images/LN_SED/40_WTH")

Tree_Nut<-read.csv2("~/NutsForSEDLN/40_WTH/Output data/Biomass/Tree data.csv", header=FALSE)

Tree_Nut_Fol<-Tree_Nut %>%
  select(V1:V15)

Tree_Nut_Fol2<-Tree_Nut_Fol %>% 
  rename("Year"=V1, "Fol_Biomass"=V3, "Month"=V2, "N_Conc"=V4, "Ca_Conc"=V5,
         "Mg_Conc"=V6, "K_Conc"=V7, "S_Conc"=V8, "P_Conc"=V9, "N_Content"=V10, "Ca_Content"=V11,
         "Mg_Content"=V12, "K_Content"=V13, "S_Content"=V14, "P_Content"=V15) 
  
Tree_Nut_Fol2[c(1:15)]<-lapply(Tree_Nut_Fol2[c(1:15)], as.numeric)

AnalysisTime<-na.omit(Tree_Nut_Fol2)

AnalysisTime<-AnalysisTime %>% mutate(Date=make_date(Year, Month))



Fol_Bio<-ggplot(AnalysisTime, aes(x=Date, y=Fol_Biomass))+geom_line()+labs(x="Date", y="Foliar Biomass (kg/ha)")+ theme_bw()+
  labs(title="Foliar Biomass")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



Ca_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Ca_Conc))+geom_line()+labs(x="Date", y=expression(Ca~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+
  labs(title="Ca Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))

N_Conc<-ggplot(AnalysisTime,aes(x=Date, y=N_Conc))+geom_line()+labs(x="Date", y=expression(N~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="N Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



P_Conc<-ggplot(AnalysisTime,aes(x=Date, y=P_Conc))+geom_line()+labs(x="Date", y=expression(P~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="P Foliar Concentration")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



S_Conc<-ggplot(AnalysisTime,aes(x=Date, y=S_Conc))+geom_line()+labs(x="Date", y=expression(S~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="S Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14),  text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


K_Conc<-ggplot(AnalysisTime,aes(x=Date, y=K_Conc))+geom_line()+labs(x="Date", y=expression(K~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+ labs(title="K Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



Mg_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Mg_Conc))+geom_line()+labs(x="Date", y=expression(Mg~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="Mg Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


windowsFonts(A = windowsFont("Times New Roman"))

ggarrange(Ca_Conc, Mg_Conc, K_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc1.png", height=1000, width=650, res=95)

ggarrange(N_Conc, P_Conc, S_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc2.png", height=1000, width=650, res=95)
```


```{r}
source("~/Project_Master/Test_Rep/Code/HN_SED/40_WTH/TreeNut_Mutator.R")


rm(list = ls())

setwd("~/Project_Master/Test_Rep/Manuscript/Images/HN_SED/40_WTH")

Tree_Nut<-read.csv2("~/NutsForSEDHN/40_WTH/Output data/Biomass/Tree data.csv", header=FALSE)

Tree_Nut_Fol<-Tree_Nut %>%
  select(V1:V15)

Tree_Nut_Fol2<-Tree_Nut_Fol %>% 
  rename("Year"=V1, "Fol_Biomass"=V3, "Month"=V2, "N_Conc"=V4, "Ca_Conc"=V5,
         "Mg_Conc"=V6, "K_Conc"=V7, "S_Conc"=V8, "P_Conc"=V9, "N_Content"=V10, "Ca_Content"=V11,
         "Mg_Content"=V12, "K_Content"=V13, "S_Content"=V14, "P_Content"=V15) 
  
Tree_Nut_Fol2[c(1:15)]<-lapply(Tree_Nut_Fol2[c(1:15)], as.numeric)

AnalysisTime<-na.omit(Tree_Nut_Fol2)

AnalysisTime<-AnalysisTime %>% mutate(Date=make_date(Year, Month))



Fol_Bio<-ggplot(AnalysisTime, aes(x=Date, y=Fol_Biomass))+geom_line()+labs(x="Date", y="Foliar Biomass (kg/ha)")+ theme_bw()+
  labs(title="Foliar Biomass")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



Ca_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Ca_Conc))+geom_line()+labs(x="Date", y=expression(Ca~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+
  labs(title="Ca Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))

N_Conc<-ggplot(AnalysisTime,aes(x=Date, y=N_Conc))+geom_line()+labs(x="Date", y=expression(N~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="N Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



P_Conc<-ggplot(AnalysisTime,aes(x=Date, y=P_Conc))+geom_line()+labs(x="Date", y=expression(P~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="P Foliar Concentration")+ 
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))



S_Conc<-ggplot(AnalysisTime,aes(x=Date, y=S_Conc))+geom_line()+labs(x="Date", y=expression(S~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="S Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14),  text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


K_Conc<-ggplot(AnalysisTime,aes(x=Date, y=K_Conc))+geom_line()+labs(x="Date", y=expression(K~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+ labs(title="K Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 1,
                                 decimal.mark = '.'))



Mg_Conc<-ggplot(AnalysisTime,aes(x=Date, y=Mg_Conc))+geom_line()+labs(x="Date", y=expression(Mg~Foliar~Concentration~(mu~mol/g)))+ theme_bw()+labs(title="Mg Foliar Concentration")+
  theme(plot.title = element_text(hjust = 0.5, size=14), text=element_text(size=12))+
  scale_y_continuous(
  labels = scales::number_format(accuracy = 0.1,
                                 decimal.mark = '.'))


windowsFonts(A = windowsFont("Times New Roman"))

ggarrange(Ca_Conc, Mg_Conc, K_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc1.png", height=1000, width=650, res=95)

ggarrange(N_Conc, P_Conc, S_Conc, labels=c("A", "B", "C"),ncol = 1, nrow = 3) %>%
  ggexport(filename="Conc2.png", height=1000, width=650, res=95)
```




