---
title: "Untitled"
author: "Kaveh"
date: "4/28/2021"
output: html_document
---

```{r}
library(dplyr)
library(lubridate)
library(ggplot2)
library(ggpubr)
library(RColorBrewer)
library(grid)
library(gridExtra)
```

```{r}
rm(list = ls())


source("~/Project_Master/Test_Rep/Code/LN_SED/40_BO/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/LN_SED/40_BO/SOM_Mutator.R")
source("~/Project_Master/Test_Rep/Code/HN_SED/40_BO/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/HN_SED/40_BO/SOM_Mutator.R")

source("~/Project_Master/Test_Rep/Code/HN_BAS/40_BO/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/HN_BAS/40_BO/SOM_Mutator.R")

source("~/Project_Master/Test_Rep/Code/LN_BAS/40_BO/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/LN_BAS/40_BO/SOM_Mutator.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/Aggregated/40_BO")

# LNS Break



SOM_LNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_SED/40_BO/Edited Data/SOM.csv")


SOM_LNS<-SOM_LNS %>%group_by(Year, Month)%>% select(-Date) %>% summarise(across(C:P, ~sum(.x, na.rm = TRUE))) %>%
  mutate(Date = make_date(Year, Month)) %>% filter(Month %in% 1)




CEC_All_LNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_SED/40_BO/Edited Data/CEC_All.csv", header=TRUE)
Litter_All_LNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_SED/40_BO/Edited Data/Litter_Pool.csv", header=TRUE)

Litter_All_LNS<-Litter_All_LNS %>% filter(Month %in% 1)


CEC_All_LNS$Date<-as.Date(CEC_All_LNS$Date)

CEC_All_LNS[, "year"] <- format(CEC_All_LNS[,"Date"], "%Y")
CEC_All_LNS[, "month"] <- format(CEC_All_LNS[,"Date"], "%m")

CEC_LNS<-CEC_All_LNS %>% group_by(year, month) %>% summarise(across(Ca:Al, ~sum(.x, na.rm=TRUE))) %>% 
  mutate(Date=make_date(year, month))%>% 
  filter(month %in% "01")

CEC_LNS$Date<-as.Date(CEC_LNS$Date)

label_color<-c("C", "Ca", "K","Mg", "N", "P", "S")
label_line<-c("dashed", "solid", "solid", "solid" ,"dashed", "dashed", "dashed")
nut_color<-c("black", "red3", "magenta2", "orange", "green2", "blue", "grey")
order<-c("Ca", "K","Mg", "C","N", "P", "S")

TimeSteps<-seq(1, 525, 1)


SOM_LNS$TS<-TimeSteps
CEC_LNS$TS<-TimeSteps
Litter_All_LNS$TS<-TimeSteps


LNS<-ggplot(CEC_LNS, aes(x=TS, y=CEC_LNS$Ca/6230.915+Litter_All_LNS$Ca/6230.915, color="Ca", linetype="Ca")) + geom_line()+
  geom_line(aes(y=CEC_LNS$Mg/2448.663+Litter_All_LNS$Mg/2448.663, color="Mg", linetype="Mg"))+
  geom_line(aes(y=CEC_LNS$K/1325.840+Litter_All_LNS$K/1325.840, color="K", linetype="K"))+
  geom_line(SOM_LNS, mapping=aes(y=N*14*10/9334.201+Litter_All_LNS$N/9334.201, color="N", linetype="N"))+
  geom_line(SOM_LNS, mapping=aes(y=P*30.974*10/667.97+Litter_All_LNS$P/667.97, color="P", linetype="P"))+
  geom_line(SOM_LNS, mapping=aes(y=S*32.065*10/754+Litter_All_LNS$S/754, color="S", linetype="S"))+
  geom_line(SOM_LNS, mapping=aes(y=(C*12*10+Litter_All_LNS$C)/142975.4, color="C", linetype="C"))+
  scale_linetype_manual(values=label_line, label=label_color)+
  scale_color_manual(values=nut_color, label=label_color)+
  theme_classic2()+
  labs(color  = "Species", linetype="Species")+
  geom_hline(yintercept= 1)+
  ggtitle("LN Sedimentary")+
  labs(x=NULL, y=NULL)+
  theme(plot.title = element_text(hjust = 0.5), legend.key.size = unit(1.5, 'cm'),  text=element_text(family="A", size=15))+
  scale_y_continuous(breaks=c(0, .25, .5, .75, 1, 1.25, 1.5, 1.75))+
  coord_cartesian(ylim = c(0, 1.5))

# HNS Break

SOM_HNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_SED/40_BO/Edited Data/SOM.csv")


SOM_HNS<-SOM_HNS %>%group_by(Year, Month)%>% select(-Date) %>% summarise(across(C:P, ~sum(.x, na.rm = TRUE))) %>%
  mutate(Date = make_date(Year, Month)) %>% filter(Month %in% 1)




CEC_All_HNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_SED/40_BO/Edited Data/CEC_All.csv", header=TRUE)
Litter_All_HNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_SED/40_BO/Edited Data/Litter_Pool.csv", header=TRUE)

Litter_All_HNS<-Litter_All_HNS %>% filter(Month %in% 1)


CEC_All_HNS$Date<-as.Date(CEC_All_HNS$Date)

CEC_All_HNS[, "year"] <- format(CEC_All_HNS[,"Date"], "%Y")
CEC_All_HNS[, "month"] <- format(CEC_All_HNS[,"Date"], "%m")

CEC_HNS<-CEC_All_HNS %>% group_by(year, month) %>% summarise(across(Ca:Al, ~sum(.x, na.rm=TRUE))) %>% 
  mutate(Date=make_date(year, month))%>% 
  filter(month %in% "01")

CEC_HNS$Date<-as.Date(CEC_HNS$Date)

SOM_HNS$TS<-TimeSteps
CEC_HNS$TS<-TimeSteps
Litter_All_HNS$TS<-TimeSteps

HNS<-ggplot(CEC_HNS, aes(x=TS, y=CEC_HNS$Ca/269.4037+Litter_All_HNS$Ca/269.4037, color="Ca", linetype="Ca")) + geom_line()+
  geom_line(aes(y=CEC_HNS$Mg/183.0244+Litter_All_HNS$Mg/183.0244, color="Mg", linetype="Mg"))+
  geom_line(aes(y=CEC_HNS$K/437.3307+Litter_All_HNS$K/437.3307, color="K", linetype="K"))+
  geom_line(SOM_HNS, mapping=aes(y=N*14*10/22247.05+Litter_All_HNS$N/22247.05, color="N", linetype="N"))+
  geom_line(SOM_HNS, mapping=aes(y=P*30.974*10/2214+Litter_All_HNS$P/2214, color="P", linetype="P"))+
  geom_line(SOM_HNS, mapping=aes(y=S*32.065*10/1271.698+Litter_All_HNS$S/1271.698, color="S", linetype="S"))+
  geom_line(SOM_HNS, mapping=aes(y=(C*12*10+Litter_All_HNS$C)/418432.9, color="C", linetype="C"))+
  scale_linetype_manual(values=label_line, label=label_color)+
  scale_color_manual(values=nut_color, label=label_color)+
  theme_classic2()+
  labs(color  = "Species", linetype="Species")+
  geom_hline(yintercept= 1)+
  ggtitle("HN Sedimentary")+
  labs(x=NULL, y=NULL)+
  theme(plot.title = element_text(hjust = 0.5), legend.key.size = unit(1.5, 'cm'),  text=element_text(family="A", size=15))+
  scale_y_continuous(breaks=c(0, .25, .5, .75, 1, 1.25, 1.5, 1.75))+
  coord_cartesian(ylim = c(0, 1.5))

# LNB Break

SOM_LNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_BAS/40_BO/Edited Data/SOM.csv")


SOM_LNB<-SOM_LNB %>%group_by(Year, Month)%>% select(-Date) %>% summarise(across(C:P, ~sum(.x, na.rm = TRUE))) %>%
  mutate(Date = make_date(Year, Month)) %>% filter(Month %in% 1)




CEC_All_LNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_BAS/40_BO/Edited Data/CEC_All.csv", header=TRUE)
Litter_All_LNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_BAS/40_BO/Edited Data/Litter_Pool.csv", header=TRUE)

Litter_All_LNB<-Litter_All_LNB %>% filter(Month %in% 1)


CEC_All_LNB$Date<-as.Date(CEC_All_LNB$Date)

CEC_All_LNB[, "year"] <- format(CEC_All_LNB[,"Date"], "%Y")
CEC_All_LNB[, "month"] <- format(CEC_All_LNB[,"Date"], "%m")

CEC_LNB<-CEC_All_LNB %>% group_by(year, month) %>% summarise(across(Ca:Al, ~sum(.x, na.rm=TRUE))) %>% 
  mutate(Date=make_date(year, month))%>% 
  filter(month %in% "01")

CEC_LNB$Date<-as.Date(CEC_LNB$Date)

SOM_LNB$TS<-TimeSteps
CEC_LNB$TS<-TimeSteps
Litter_All_LNB$TS<-TimeSteps

LNB<-ggplot(CEC_LNB, aes(x=TS, y=CEC_LNB$Ca/3364.286+Litter_All_LNB$Ca/3364.286, color="Ca", linetype="Ca")) + geom_line()+
  geom_line(aes(y=CEC_LNB$Mg/3404.168+Litter_All_LNB$Mg/3404.168, color="Mg", linetype="Mg"))+
  geom_line(aes(y=CEC_LNB$K/880.0967+Litter_All_LNB$K/880.0967, color="K", linetype="K"))+
  geom_line(SOM_LNB, mapping=aes(y=N*14*10/9205.251+Litter_All_LNB$N/9205.251, color="N", linetype="N"))+
  geom_line(SOM_LNB, mapping=aes(y=P*30.974*10/643.33+Litter_All_LNB$P/643.33, color="P", linetype="P"))+
  geom_line(SOM_LNB, mapping=aes(y=S*32.065*10/824.22+Litter_All_LNB$S/824.22, color="S", linetype="S"))+
  geom_line(SOM_LNB, mapping=aes(y=(C*12*10+Litter_All_LNB$C)/154973.3, color="C", linetype="C"))+
  scale_linetype_manual(values=label_line, label=label_color)+
  scale_color_manual(values=nut_color, label=label_color)+
  theme_classic2()+
  labs(color  = "Species", linetype="Species")+
  geom_hline(yintercept= 1)+
  ggtitle("LN Basalt")+
  labs(x=NULL, y=NULL)+
  theme(plot.title = element_text(hjust = 0.5), legend.key.size = unit(1.5, 'cm'),  text=element_text(family="A", size=15))+
  scale_y_continuous(breaks=c(0, .25, .5, .75, 1, 1.25, 1.5, 1.75))+
  coord_cartesian(ylim = c(0, 1.5))

# HNB Break 

SOM_HNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_BAS/40_BO/Edited Data/SOM.csv")


SOM_HNB<-SOM_HNB %>%group_by(Year, Month)%>% select(-Date) %>% summarise(across(C:P, ~sum(.x, na.rm = TRUE))) %>%
  mutate(Date = make_date(Year, Month)) %>% filter(Month %in% 1)




CEC_All_HNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_BAS/40_BO/Edited Data/CEC_All.csv", header=TRUE)
Litter_All_HNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_BAS/40_BO/Edited Data/Litter_Pool.csv", header=TRUE)

Litter_All_HNB<-Litter_All_HNB %>% filter(Month %in% 1)


CEC_All_HNB$Date<-as.Date(CEC_All_HNB$Date)

CEC_All_HNB[, "year"] <- format(CEC_All_HNB[,"Date"], "%Y")
CEC_All_HNB[, "month"] <- format(CEC_All_HNB[,"Date"], "%m")

CEC_HNB<-CEC_All_HNB %>% group_by(year, month) %>% summarise(across(Ca:Al, ~sum(.x, na.rm=TRUE))) %>% 
  mutate(Date=make_date(year, month))%>% 
  filter(month %in% "01")

CEC_HNB$Date<-as.Date(CEC_HNB$Date)

SOM_HNB$TS<-TimeSteps
CEC_HNB$TS<-TimeSteps
Litter_All_HNB$TS<-TimeSteps

HNB<-ggplot(CEC_HNB, aes(x=TS, y=CEC_HNB$Ca/232.34+Litter_All_HNB$Ca/232.34, color="Ca", linetype="Ca")) + geom_line()+
  geom_line(aes(y=CEC_HNB$Mg/267.2+Litter_All_HNB$Mg/267.2, color="Mg", linetype="Mg"))+
  geom_line(aes(y=CEC_HNB$K/163.11+Litter_All_HNB$K/163.11, color="K", linetype="K"))+
  geom_line(SOM_HNB, mapping=aes(y=N*14*10/16757+Litter_All_HNB$N/16757, color="N", linetype="N"))+
  geom_line(SOM_HNB, mapping=aes(y=P*30.974*10/1242.458+Litter_All_HNB$P/1242.458, color="P", linetype="P"))+
  geom_line(SOM_HNB, mapping=aes(y=S*32.065*10/699.88+Litter_All_HNB$S/699.88, color="S", linetype="S"))+
  geom_line(SOM_HNB, mapping=aes(y=(C*12*10+Litter_All_HNB$C)/275094.6, color="C", linetype="C"))+
  scale_linetype_manual(values=label_line, label=label_color)+
  scale_color_manual(values=nut_color, label=label_color)+
  theme_classic2()+
  labs(color  = "Species", linetype="Species")+
  geom_hline(yintercept= 1)+
  ggtitle("HN Basalt")+
  labs(x=NULL, y=NULL)+
  theme(plot.title = element_text(hjust = 0.5), legend.key.size = unit(1.5, 'cm'),  text=element_text(family="A", size=15))+
  scale_y_continuous(breaks=c(0, .25, .5, .75, 1, 1.25, 1.5, 1.75))+
  coord_cartesian(ylim = c(0, 1.5))

# BEEMP

Color_C<-c(expression(C[Litter]),expression(C[SOM]))

C_LNS<-ggplot(SOM_LNS, aes(x=TS, y=C*12*10000/1000/1000, color="CSOM"))+geom_line()+
  geom_line(Litter_All_LNS, mapping= aes(x=TS, y=C/1000, color="CLit"))+
  ggtitle("Low N Sedimentary")+
  labs(x=NULL, y=NULL, color='C Pool')+
  scale_color_manual(values=c("red", "green"),label = Color_C)+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))

C_LNB<-ggplot(SOM_LNB, aes(x=TS, y=C*12*10000/1000/1000, color="CSOM"))+geom_line()+
  geom_line(Litter_All_LNB, mapping= aes(x=TS, y=C/1000, color="CLit"))+
  ggtitle("Low N Basalt")+
  labs(x=NULL, y=NULL, color='C Pool')+
  scale_color_manual(values=c("red", "green"),label = Color_C)+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))


C_HNS<-ggplot(SOM_HNS, aes(x=TS, y=C*12*10000/1000/1000, color="CSOM"))+geom_line()+
  geom_line(Litter_All_HNS, mapping= aes(x=TS, y=C/1000, color="CLit"))+
  ggtitle("High N Sedimentary")+
  labs(x=NULL, y=NULL, color='C Pool')+
  scale_color_manual(values=c("red", "green"),label = Color_C)+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))

C_HNB<-ggplot(SOM_HNB, aes(x=TS, y=C*12*10000/1000/1000, color="CSOM"))+geom_line()+
  geom_line(Litter_All_HNB, mapping= aes(x=TS, y=C/1000, color="CLit"))+
  ggtitle("High N Basalt")+
  labs(x=NULL, y=NULL, color='C Pool')+
  scale_color_manual(values=c("red", "green"),label = Color_C)+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))




# Aggregate

ggarrange(C_LNS, C_HNS, C_LNB, C_HNB, labels=c("A", "B", "C", "D"),
          ncol = 2, nrow = 2, common.legend = TRUE, legend="right", heights =1, widths = 1)%>%
  annotate_figure(left = textGrob("Carbon Pool Size (Mg/ha)", rot = 90, vjust=.45, gp = gpar(cex = 1.3,
                    font.label = list(size = 14, color = "black", face = "bold"))),
                    bottom = textGrob("Time Step (Years)", gp = gpar(cex = 1.3)), top=textGrob("40 BO")) %>%
  ggexport(filename="C_Pool.png", height=1000, width=1000, res=100)


ggarrange(LNS, HNS, LNB, HNB, labels=c("A", "B", "C", "D"),
          ncol = 2, nrow = 2, common.legend = TRUE, legend="right", heights =1, widths = 1)%>%
  annotate_figure(left = textGrob("Nutrient Pool Size", rot = 90, vjust=.45, gp = gpar(cex = 1.3,
                    font.label = list(size = 14, color = "black", face = "bold"))),
                    bottom = textGrob("Time Step (Years)", gp = gpar(cex = 1.3)), top=textGrob("40 BO")) %>%
  ggexport(filename="Nutrient_Pool.png", height=1000, width=1000, res=100)

```



```{r}
rm(list = ls())


source("~/Project_Master/Test_Rep/Code/LN_SED/40_WTH/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/LN_SED/40_WTH/SOM_Mutator.R")
source("~/Project_Master/Test_Rep/Code/HN_SED/40_WTH/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/HN_SED/40_WTH/SOM_Mutator.R")

source("~/Project_Master/Test_Rep/Code/HN_BAS/40_WTH/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/HN_BAS/40_WTH/SOM_Mutator.R")

source("~/Project_Master/Test_Rep/Code/LN_BAS/40_WTH/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/LN_BAS/40_WTH/SOM_Mutator.R")

label_color<-c("Ca", "K", "Mg", expression(N[O]), expression(P[O]), expression(S[O]))

setwd("~/Project_Master/Test_Rep/Manuscript/Images/Aggregated/40_WTH")

# LNS Break

SOM_LNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_SED/40_WTH/Edited Data/SOM.csv")


SOM_LNS<-SOM_LNS %>%group_by(Year, Month)%>% select(-Date) %>% summarise(across(C:P, ~sum(.x, na.rm = TRUE))) %>%
  mutate(Date = make_date(Year, Month)) %>% filter(Month %in% 1)




CEC_All_LNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_SED/40_WTH/Edited Data/CEC_All.csv", header=TRUE)
Litter_All_LNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_SED/40_WTH/Edited Data/Litter_Pool.csv", header=TRUE)

Litter_All_LNS<-Litter_All_LNS %>% filter(Month %in% 1)


CEC_All_LNS$Date<-as.Date(CEC_All_LNS$Date)

CEC_All_LNS[, "year"] <- format(CEC_All_LNS[,"Date"], "%Y")
CEC_All_LNS[, "month"] <- format(CEC_All_LNS[,"Date"], "%m")

CEC_LNS<-CEC_All_LNS %>% group_by(year, month) %>% summarise(across(Ca:Al, ~sum(.x, na.rm=TRUE))) %>% 
  mutate(Date=make_date(year, month))%>% 
  filter(month %in% "01")

CEC_LNS$Date<-as.Date(CEC_LNS$Date)

label_color<-c("C", "Ca", "K","Mg", "N", "P", "S")
label_line<-c("dashed", "solid", "solid", "solid" ,"dashed", "dashed", "dashed")
nut_color<-c("black", "red3", "magenta2", "orange", "green2", "blue", "grey")
order<-c("Ca", "K","Mg", "C","N", "P", "S")

TimeSteps<-seq(1, 525, 1)


SOM_LNS$TS<-TimeSteps
CEC_LNS$TS<-TimeSteps
Litter_All_LNS$TS<-TimeSteps


LNS<-ggplot(CEC_LNS, aes(x=TS, y=CEC_LNS$Ca/6230.915+Litter_All_LNS$Ca/6230.915, color="Ca", linetype="Ca")) + geom_line()+
  geom_line(aes(y=CEC_LNS$Mg/2448.663+Litter_All_LNS$Mg/2448.663, color="Mg", linetype="Mg"))+
  geom_line(aes(y=CEC_LNS$K/1325.840+Litter_All_LNS$K/1325.840, color="K", linetype="K"))+
  geom_line(SOM_LNS, mapping=aes(y=N*14*10/9334.201+Litter_All_LNS$N/9334.201, color="N", linetype="N"))+
  geom_line(SOM_LNS, mapping=aes(y=P*30.974*10/667.97+Litter_All_LNS$P/667.97, color="P", linetype="P"))+
  geom_line(SOM_LNS, mapping=aes(y=S*32.065*10/754+Litter_All_LNS$S/754, color="S", linetype="S"))+
  geom_line(SOM_LNS, mapping=aes(y=(C*12*10+Litter_All_LNS$C)/142975.4, color="C", linetype="C"))+
  scale_linetype_manual(values=label_line, label=label_color)+
  scale_color_manual(values=nut_color, label=label_color)+
  theme_classic2()+
  labs(color  = "Species", linetype="Species")+
  geom_hline(yintercept= 1)+
  ggtitle("LN Sedimentary")+
  labs(x=NULL, y=NULL)+
  theme(plot.title = element_text(hjust = 0.5), legend.key.size = unit(1.5, 'cm'),  text=element_text(family="A", size=15))+
  scale_y_continuous(breaks=c(0, .25, .5, .75, 1, 1.25, 1.5, 1.75))+
  coord_cartesian(ylim = c(0, 1.5))

# HNS Break

SOM_HNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_SED/40_WTH/Edited Data/SOM.csv")


SOM_HNS<-SOM_HNS %>%group_by(Year, Month)%>% select(-Date) %>% summarise(across(C:P, ~sum(.x, na.rm = TRUE))) %>%
  mutate(Date = make_date(Year, Month)) %>% filter(Month %in% 1)




CEC_All_HNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_SED/40_WTH/Edited Data/CEC_All.csv", header=TRUE)
Litter_All_HNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_SED/40_WTH/Edited Data/Litter_Pool.csv", header=TRUE)

Litter_All_HNS<-Litter_All_HNS %>% filter(Month %in% 1)


CEC_All_HNS$Date<-as.Date(CEC_All_HNS$Date)

CEC_All_HNS[, "year"] <- format(CEC_All_HNS[,"Date"], "%Y")
CEC_All_HNS[, "month"] <- format(CEC_All_HNS[,"Date"], "%m")

CEC_HNS<-CEC_All_HNS %>% group_by(year, month) %>% summarise(across(Ca:Al, ~sum(.x, na.rm=TRUE))) %>% 
  mutate(Date=make_date(year, month))%>% 
  filter(month %in% "01")

CEC_HNS$Date<-as.Date(CEC_HNS$Date)

SOM_HNS$TS<-TimeSteps
CEC_HNS$TS<-TimeSteps
Litter_All_HNS$TS<-TimeSteps

HNS<-ggplot(CEC_HNS, aes(x=TS, y=CEC_HNS$Ca/269.4037+Litter_All_HNS$Ca/269.4037, color="Ca", linetype="Ca")) + geom_line()+
  geom_line(aes(y=CEC_HNS$Mg/183.0244+Litter_All_HNS$Mg/183.0244, color="Mg", linetype="Mg"))+
  geom_line(aes(y=CEC_HNS$K/437.3307+Litter_All_HNS$K/437.3307, color="K", linetype="K"))+
  geom_line(SOM_HNS, mapping=aes(y=N*14*10/22247.05+Litter_All_HNS$N/22247.05, color="N", linetype="N"))+
  geom_line(SOM_HNS, mapping=aes(y=P*30.974*10/2214+Litter_All_HNS$P/2214, color="P", linetype="P"))+
  geom_line(SOM_HNS, mapping=aes(y=S*32.065*10/1271.698+Litter_All_HNS$S/1271.698, color="S", linetype="S"))+
  geom_line(SOM_HNS, mapping=aes(y=(C*12*10+Litter_All_HNS$C)/418432.9, color="C", linetype="C"))+
  scale_linetype_manual(values=label_line, label=label_color)+
  scale_color_manual(values=nut_color, label=label_color)+
  theme_classic2()+
  labs(color  = "Species", linetype="Species")+
  geom_hline(yintercept= 1)+
  ggtitle("HN Sedimentary")+
  labs(x=NULL, y=NULL)+
  theme(plot.title = element_text(hjust = 0.5), legend.key.size = unit(1.5, 'cm'),  text=element_text(family="A", size=15))+
  scale_y_continuous(breaks=c(0, .25, .5, .75, 1, 1.25, 1.5, 1.75))+
  coord_cartesian(ylim = c(0, 1.5))

# LNB Break

SOM_LNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_BAS/40_WTH/Edited Data/SOM.csv")


SOM_LNB<-SOM_LNB %>%group_by(Year, Month)%>% select(-Date) %>% summarise(across(C:P, ~sum(.x, na.rm = TRUE))) %>%
  mutate(Date = make_date(Year, Month)) %>% filter(Month %in% 1)




CEC_All_LNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_BAS/40_WTH/Edited Data/CEC_All.csv", header=TRUE)
Litter_All_LNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_BAS/40_WTH/Edited Data/Litter_Pool.csv", header=TRUE)

Litter_All_LNB<-Litter_All_LNB %>% filter(Month %in% 1)


CEC_All_LNB$Date<-as.Date(CEC_All_LNB$Date)

CEC_All_LNB[, "year"] <- format(CEC_All_LNB[,"Date"], "%Y")
CEC_All_LNB[, "month"] <- format(CEC_All_LNB[,"Date"], "%m")

CEC_LNB<-CEC_All_LNB %>% group_by(year, month) %>% summarise(across(Ca:Al, ~sum(.x, na.rm=TRUE))) %>% 
  mutate(Date=make_date(year, month))%>% 
  filter(month %in% "01")

CEC_LNB$Date<-as.Date(CEC_LNB$Date)

SOM_LNB$TS<-TimeSteps
CEC_LNB$TS<-TimeSteps
Litter_All_LNB$TS<-TimeSteps

LNB<-ggplot(CEC_LNB, aes(x=TS, y=CEC_LNB$Ca/3364.286+Litter_All_LNB$Ca/3364.286, color="Ca", linetype="Ca")) + geom_line()+
  geom_line(aes(y=CEC_LNB$Mg/3404.168+Litter_All_LNB$Mg/3404.168, color="Mg", linetype="Mg"))+
  geom_line(aes(y=CEC_LNB$K/880.0967+Litter_All_LNB$K/880.0967, color="K", linetype="K"))+
  geom_line(SOM_LNB, mapping=aes(y=N*14*10/9205.251+Litter_All_LNB$N/9205.251, color="N", linetype="N"))+
  geom_line(SOM_LNB, mapping=aes(y=P*30.974*10/643.33+Litter_All_LNB$P/643.33, color="P", linetype="P"))+
  geom_line(SOM_LNB, mapping=aes(y=S*32.065*10/824.22+Litter_All_LNB$S/824.22, color="S", linetype="S"))+
  geom_line(SOM_LNB, mapping=aes(y=(C*12*10+Litter_All_LNB$C)/154973.3, color="C", linetype="C"))+
  scale_linetype_manual(values=label_line, label=label_color)+
  scale_color_manual(values=nut_color, label=label_color)+
  theme_classic2()+
  labs(color  = "Species", linetype="Species")+
  geom_hline(yintercept= 1)+
  ggtitle("LN Basalt")+
  labs(x=NULL, y=NULL)+
  theme(plot.title = element_text(hjust = 0.5), legend.key.size = unit(1.5, 'cm'),  text=element_text(family="A", size=15))+
  scale_y_continuous(breaks=c(0, .25, .5, .75, 1, 1.25, 1.5, 1.75))+
  coord_cartesian(ylim = c(0, 1.5))

# HNB Break 

SOM_HNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_BAS/40_WTH/Edited Data/SOM.csv")


SOM_HNB<-SOM_HNB %>%group_by(Year, Month)%>% select(-Date) %>% summarise(across(C:P, ~sum(.x, na.rm = TRUE))) %>%
  mutate(Date = make_date(Year, Month)) %>% filter(Month %in% 1)




CEC_All_HNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_BAS/40_WTH/Edited Data/CEC_All.csv", header=TRUE)
Litter_All_HNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_BAS/40_WTH/Edited Data/Litter_Pool.csv", header=TRUE)

Litter_All_HNB<-Litter_All_HNB %>% filter(Month %in% 1)


CEC_All_HNB$Date<-as.Date(CEC_All_HNB$Date)

CEC_All_HNB[, "year"] <- format(CEC_All_HNB[,"Date"], "%Y")
CEC_All_HNB[, "month"] <- format(CEC_All_HNB[,"Date"], "%m")

CEC_HNB<-CEC_All_HNB %>% group_by(year, month) %>% summarise(across(Ca:Al, ~sum(.x, na.rm=TRUE))) %>% 
  mutate(Date=make_date(year, month))%>% 
  filter(month %in% "01")

CEC_HNB$Date<-as.Date(CEC_HNB$Date)

SOM_HNB$TS<-TimeSteps
CEC_HNB$TS<-TimeSteps
Litter_All_HNB$TS<-TimeSteps

HNB<-ggplot(CEC_HNB, aes(x=TS, y=CEC_HNB$Ca/232.34+Litter_All_HNB$Ca/232.34, color="Ca", linetype="Ca")) + geom_line()+
  geom_line(aes(y=CEC_HNB$Mg/267.2+Litter_All_HNB$Mg/267.2, color="Mg", linetype="Mg"))+
  geom_line(aes(y=CEC_HNB$K/163.11+Litter_All_HNB$K/163.11, color="K", linetype="K"))+
  geom_line(SOM_HNB, mapping=aes(y=N*14*10/16757+Litter_All_HNB$N/16757, color="N", linetype="N"))+
  geom_line(SOM_HNB, mapping=aes(y=P*30.974*10/1242.458+Litter_All_HNB$P/1242.458, color="P", linetype="P"))+
  geom_line(SOM_HNB, mapping=aes(y=S*32.065*10/699.88+Litter_All_HNB$S/699.88, color="S", linetype="S"))+
  geom_line(SOM_HNB, mapping=aes(y=(C*12*10+Litter_All_HNB$C)/275094.6, color="C", linetype="C"))+
  scale_linetype_manual(values=label_line, label=label_color)+
  scale_color_manual(values=nut_color, label=label_color)+
  theme_classic2()+
  labs(color  = "Species", linetype="Species")+
  geom_hline(yintercept= 1)+
  ggtitle("HN Basalt")+
  labs(x=NULL, y=NULL)+
  theme(plot.title = element_text(hjust = 0.5), legend.key.size = unit(1.5, 'cm'),  text=element_text(family="A", size=15))+
  scale_y_continuous(breaks=c(0, .25, .5, .75, 1, 1.25, 1.5, 1.75))+
  coord_cartesian(ylim = c(0, 1.5))




Color_C<-c(expression(C[Litter]),expression(C[SOM]))

C_LNS<-ggplot(SOM_LNS, aes(x=TS, y=C*12*10000/1000/1000, color="CSOM"))+geom_line()+
  geom_line(Litter_All_LNS, mapping= aes(x=TS, y=C/1000, color="CLit"))+
  ggtitle("Low N Sedimentary")+
  labs(x=NULL, y=NULL, color='C Pool')+
  scale_color_manual(values=c("red", "green"),label = Color_C)+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))

C_LNB<-ggplot(SOM_LNB, aes(x=TS, y=C*12*10000/1000/1000, color="CSOM"))+geom_line()+
  geom_line(Litter_All_LNB, mapping= aes(x=TS, y=C/1000, color="CLit"))+
  ggtitle("Low N Basalt")+
  labs(x=NULL, y=NULL, color='C Pool')+
  scale_color_manual(values=c("red", "green"),label = Color_C)+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))


C_HNS<-ggplot(SOM_HNS, aes(x=TS, y=C*12*10000/1000/1000, color="CSOM"))+geom_line()+
  geom_line(Litter_All_HNS, mapping= aes(x=TS, y=C/1000, color="CLit"))+
  ggtitle("High N Sedimentary")+
  labs(x=NULL, y=NULL, color='C Pool')+
  scale_color_manual(values=c("red", "green"),label = Color_C)+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))

C_HNB<-ggplot(SOM_HNB, aes(x=TS, y=C*12*10000/1000/1000, color="CSOM"))+geom_line()+
  geom_line(Litter_All_HNB, mapping= aes(x=TS, y=C/1000, color="CLit"))+
  ggtitle("High N Basalt")+
  labs(x=NULL, y=NULL, color='C Pool')+
  scale_color_manual(values=c("red", "green"),label = Color_C)+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))




# Aggregate

ggarrange(C_LNS, C_HNS, C_LNB, C_HNB, labels=c("A", "B", "C", "D"),
          ncol = 2, nrow = 2, common.legend = TRUE, legend="right", heights =1, widths = 1)%>%
  annotate_figure(left = textGrob("Carbon Pool Size (Mg/ha)", rot = 90, vjust=.45, gp = gpar(cex = 1.3,
                    font.label = list(size = 14, color = "black", face = "bold"))),
                    bottom = textGrob("Time Step (Years)", gp = gpar(cex = 1.3)), top=textGrob("40 BO")) %>%
  ggexport(filename="C_Pool.png", height=1000, width=1000, res=100)




ggarrange(LNS, HNS, LNB, HNB, labels=c("A", "B", "C", "D"),
          ncol = 2, nrow = 2, common.legend = TRUE, legend="right", heights =1, widths = 1)%>%
  annotate_figure(left = textGrob("Nutrient Pool Size", rot = 90, vjust=.45, gp = gpar(cex = 1.3,
                    font.label = list(size = 14, color = "black", face = "bold"))),
                    bottom = textGrob("Time Step (Years)", gp = gpar(cex = 1.3)), top=textGrob("40 WTH")) %>%
  ggexport(filename="Nutrient_Pool.png", height=1000, width=1000, res=100)


```

```{r}
rm(list = ls())


source("~/Project_Master/Test_Rep/Code/LN_SED/80_BO/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/LN_SED/80_BO/SOM_Mutator.R")
source("~/Project_Master/Test_Rep/Code/HN_SED/80_BO/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/HN_SED/80_BO/SOM_Mutator.R")

source("~/Project_Master/Test_Rep/Code/HN_BAS/80_BO/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/HN_BAS/80_BO/SOM_Mutator.R")

source("~/Project_Master/Test_Rep/Code/LN_BAS/80_BO/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/LN_BAS/80_BO/SOM_Mutator.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/Aggregated/80_BO")

label_color<-c("Ca", "K", "Mg", expression(N[O]), expression(P[O]), expression(S[O]))

# LNS Break

SOM_LNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_SED/80_BO/Edited Data/SOM.csv")


SOM_LNS<-SOM_LNS %>%group_by(Year, Month)%>% select(-Date) %>% summarise(across(C:P, ~sum(.x, na.rm = TRUE))) %>%
  mutate(Date = make_date(Year, Month)) %>% filter(Month %in% 1)




CEC_All_LNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_SED/80_BO/Edited Data/CEC_All.csv", header=TRUE)
Litter_All_LNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_SED/80_BO/Edited Data/Litter_Pool.csv", header=TRUE)

Litter_All_LNS<-Litter_All_LNS %>% filter(Month %in% 1)


CEC_All_LNS$Date<-as.Date(CEC_All_LNS$Date)

CEC_All_LNS[, "year"] <- format(CEC_All_LNS[,"Date"], "%Y")
CEC_All_LNS[, "month"] <- format(CEC_All_LNS[,"Date"], "%m")

CEC_LNS<-CEC_All_LNS %>% group_by(year, month) %>% summarise(across(Ca:Al, ~sum(.x, na.rm=TRUE))) %>% 
  mutate(Date=make_date(year, month))%>% 
  filter(month %in% "01")

CEC_LNS$Date<-as.Date(CEC_LNS$Date)

label_color<-c("C", "Ca", "K","Mg", "N", "P", "S")
label_line<-c("dashed", "solid", "solid", "solid" ,"dashed", "dashed", "dashed")
nut_color<-c("black", "red3", "magenta2", "orange", "green2", "blue", "grey")
order<-c("Ca", "K","Mg", "C","N", "P", "S")

TimeSteps<-seq(1, 513, 1)


SOM_LNS$TS<-TimeSteps
CEC_LNS$TS<-TimeSteps
Litter_All_LNS$TS<-TimeSteps


LNS<-ggplot(CEC_LNS, aes(x=TS, y=CEC_LNS$Ca/6230.915+Litter_All_LNS$Ca/6230.915, color="Ca", linetype="Ca")) + geom_line()+
  geom_line(aes(y=CEC_LNS$Mg/2448.663+Litter_All_LNS$Mg/2448.663, color="Mg", linetype="Mg"))+
  geom_line(aes(y=CEC_LNS$K/1325.840+Litter_All_LNS$K/1325.840, color="K", linetype="K"))+
  geom_line(SOM_LNS, mapping=aes(y=N*14*10/9334.201+Litter_All_LNS$N/9334.201, color="N", linetype="N"))+
  geom_line(SOM_LNS, mapping=aes(y=P*30.974*10/667.97+Litter_All_LNS$P/667.97, color="P", linetype="P"))+
  geom_line(SOM_LNS, mapping=aes(y=S*32.065*10/754+Litter_All_LNS$S/754, color="S", linetype="S"))+
  geom_line(SOM_LNS, mapping=aes(y=(C*12*10+Litter_All_LNS$C)/142975.4, color="C", linetype="C"))+
  scale_linetype_manual(values=label_line, label=label_color)+
  scale_color_manual(values=nut_color, label=label_color)+
  theme_classic2()+
  labs(color  = "Species", linetype="Species")+
  geom_hline(yintercept= 1)+
  ggtitle("LN Sedimentary")+
  labs(x=NULL, y=NULL)+
  theme(plot.title = element_text(hjust = 0.5), legend.key.size = unit(1.5, 'cm'),  text=element_text(family="A", size=15))+
  scale_y_continuous(breaks=c(0, .25, .5, .75, 1, 1.25, 1.5, 1.75))+
  coord_cartesian(ylim = c(0, 1.5))

# HNS Break

SOM_HNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_SED/80_BO/Edited Data/SOM.csv")


SOM_HNS<-SOM_HNS %>%group_by(Year, Month)%>% select(-Date) %>% summarise(across(C:P, ~sum(.x, na.rm = TRUE))) %>%
  mutate(Date = make_date(Year, Month)) %>% filter(Month %in% 1)




CEC_All_HNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_SED/80_BO/Edited Data/CEC_All.csv", header=TRUE)
Litter_All_HNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_SED/80_BO/Edited Data/Litter_Pool.csv", header=TRUE)

Litter_All_HNS<-Litter_All_HNS %>% filter(Month %in% 1)


CEC_All_HNS$Date<-as.Date(CEC_All_HNS$Date)

CEC_All_HNS[, "year"] <- format(CEC_All_HNS[,"Date"], "%Y")
CEC_All_HNS[, "month"] <- format(CEC_All_HNS[,"Date"], "%m")

CEC_HNS<-CEC_All_HNS %>% group_by(year, month) %>% summarise(across(Ca:Al, ~sum(.x, na.rm=TRUE))) %>% 
  mutate(Date=make_date(year, month))%>% 
  filter(month %in% "01")

CEC_HNS$Date<-as.Date(CEC_HNS$Date)

SOM_HNS$TS<-TimeSteps
CEC_HNS$TS<-TimeSteps
Litter_All_HNS$TS<-TimeSteps

HNS<-ggplot(CEC_HNS, aes(x=TS, y=CEC_HNS$Ca/269.4037+Litter_All_HNS$Ca/269.4037, color="Ca", linetype="Ca")) + geom_line()+
  geom_line(aes(y=CEC_HNS$Mg/183.0244+Litter_All_HNS$Mg/183.0244, color="Mg", linetype="Mg"))+
  geom_line(aes(y=CEC_HNS$K/437.3307+Litter_All_HNS$K/437.3307, color="K", linetype="K"))+
  geom_line(SOM_HNS, mapping=aes(y=N*14*10/22247.05+Litter_All_HNS$N/22247.05, color="N", linetype="N"))+
  geom_line(SOM_HNS, mapping=aes(y=P*30.974*10/2214+Litter_All_HNS$P/2214, color="P", linetype="P"))+
  geom_line(SOM_HNS, mapping=aes(y=S*32.065*10/1271.698+Litter_All_HNS$S/1271.698, color="S", linetype="S"))+
  geom_line(SOM_HNS, mapping=aes(y=(C*12*10+Litter_All_HNS$C)/418432.9, color="C", linetype="C"))+
  scale_linetype_manual(values=label_line, label=label_color)+
  scale_color_manual(values=nut_color, label=label_color)+
  theme_classic2()+
  labs(color  = "Species", linetype="Species")+
  geom_hline(yintercept= 1)+
  ggtitle("HN Sedimentary")+
  labs(x=NULL, y=NULL)+
  theme(plot.title = element_text(hjust = 0.5), legend.key.size = unit(1.5, 'cm'),  text=element_text(family="A", size=15))+
  scale_y_continuous(breaks=c(0, .25, .5, .75, 1, 1.25, 1.5, 1.75))+
  coord_cartesian(ylim = c(0, 1.5))

# LNB Break

SOM_LNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_BAS/80_BO/Edited Data/SOM.csv")


SOM_LNB<-SOM_LNB %>%group_by(Year, Month)%>% select(-Date) %>% summarise(across(C:P, ~sum(.x, na.rm = TRUE))) %>%
  mutate(Date = make_date(Year, Month)) %>% filter(Month %in% 1)




CEC_All_LNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_BAS/80_BO/Edited Data/CEC_All.csv", header=TRUE)
Litter_All_LNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_BAS/80_BO/Edited Data/Litter_Pool.csv", header=TRUE)

Litter_All_LNB<-Litter_All_LNB %>% filter(Month %in% 1)


CEC_All_LNB$Date<-as.Date(CEC_All_LNB$Date)

CEC_All_LNB[, "year"] <- format(CEC_All_LNB[,"Date"], "%Y")
CEC_All_LNB[, "month"] <- format(CEC_All_LNB[,"Date"], "%m")

CEC_LNB<-CEC_All_LNB %>% group_by(year, month) %>% summarise(across(Ca:Al, ~sum(.x, na.rm=TRUE))) %>% 
  mutate(Date=make_date(year, month))%>% 
  filter(month %in% "01")

CEC_LNB$Date<-as.Date(CEC_LNB$Date)

SOM_LNB$TS<-TimeSteps
CEC_LNB$TS<-TimeSteps
Litter_All_LNB$TS<-TimeSteps

LNB<-ggplot(CEC_LNB, aes(x=TS, y=CEC_LNB$Ca/3364.286+Litter_All_LNB$Ca/3364.286, color="Ca", linetype="Ca")) + geom_line()+
  geom_line(aes(y=CEC_LNB$Mg/3404.168+Litter_All_LNB$Mg/3404.168, color="Mg", linetype="Mg"))+
  geom_line(aes(y=CEC_LNB$K/880.0967+Litter_All_LNB$K/880.0967, color="K", linetype="K"))+
  geom_line(SOM_LNB, mapping=aes(y=N*14*10/9205.251+Litter_All_LNB$N/9205.251, color="N", linetype="N"))+
  geom_line(SOM_LNB, mapping=aes(y=P*30.974*10/643.33+Litter_All_LNB$P/643.33, color="P", linetype="P"))+
  geom_line(SOM_LNB, mapping=aes(y=S*32.065*10/824.22+Litter_All_LNB$S/824.22, color="S", linetype="S"))+
  geom_line(SOM_LNB, mapping=aes(y=(C*12*10+Litter_All_LNB$C)/154973.3, color="C", linetype="C"))+
  scale_linetype_manual(values=label_line, label=label_color)+
  scale_color_manual(values=nut_color, label=label_color)+
  theme_classic2()+
  labs(color  = "Species", linetype="Species")+
  geom_hline(yintercept= 1)+
  ggtitle("LN Basalt")+
  labs(x=NULL, y=NULL)+
  theme(plot.title = element_text(hjust = 0.5), legend.key.size = unit(1.5, 'cm'),  text=element_text(family="A", size=15))+
  scale_y_continuous(breaks=c(0, .25, .5, .75, 1, 1.25, 1.5, 1.75))+
  coord_cartesian(ylim = c(0, 1.5))

# HNB Break 

SOM_HNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_BAS/80_BO/Edited Data/SOM.csv")


SOM_HNB<-SOM_HNB %>%group_by(Year, Month)%>% select(-Date) %>% summarise(across(C:P, ~sum(.x, na.rm = TRUE))) %>%
  mutate(Date = make_date(Year, Month)) %>% filter(Month %in% 1)




CEC_All_HNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_BAS/80_BO/Edited Data/CEC_All.csv", header=TRUE)
Litter_All_HNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_BAS/80_BO/Edited Data/Litter_Pool.csv", header=TRUE)

Litter_All_HNB<-Litter_All_HNB %>% filter(Month %in% 1)


CEC_All_HNB$Date<-as.Date(CEC_All_HNB$Date)

CEC_All_HNB[, "year"] <- format(CEC_All_HNB[,"Date"], "%Y")
CEC_All_HNB[, "month"] <- format(CEC_All_HNB[,"Date"], "%m")

CEC_HNB<-CEC_All_HNB %>% group_by(year, month) %>% summarise(across(Ca:Al, ~sum(.x, na.rm=TRUE))) %>% 
  mutate(Date=make_date(year, month))%>% 
  filter(month %in% "01")

CEC_HNB$Date<-as.Date(CEC_HNB$Date)

SOM_HNB$TS<-TimeSteps
CEC_HNB$TS<-TimeSteps
Litter_All_HNB$TS<-TimeSteps

HNB<-ggplot(CEC_HNB, aes(x=TS, y=CEC_HNB$Ca/232.34+Litter_All_HNB$Ca/232.34, color="Ca", linetype="Ca")) + geom_line()+
  geom_line(aes(y=CEC_HNB$Mg/267.2+Litter_All_HNB$Mg/267.2, color="Mg", linetype="Mg"))+
  geom_line(aes(y=CEC_HNB$K/163.11+Litter_All_HNB$K/163.11, color="K", linetype="K"))+
  geom_line(SOM_HNB, mapping=aes(y=N*14*10/16757+Litter_All_HNB$N/16757, color="N", linetype="N"))+
  geom_line(SOM_HNB, mapping=aes(y=P*30.974*10/1242.458+Litter_All_HNB$P/1242.458, color="P", linetype="P"))+
  geom_line(SOM_HNB, mapping=aes(y=S*32.065*10/699.88+Litter_All_HNB$S/699.88, color="S", linetype="S"))+
  geom_line(SOM_HNB, mapping=aes(y=(C*12*10+Litter_All_HNB$C)/275094.6, color="C", linetype="C"))+
  scale_linetype_manual(values=label_line, label=label_color)+
  scale_color_manual(values=nut_color, label=label_color)+
  theme_classic2()+
  labs(color  = "Species", linetype="Species")+
  geom_hline(yintercept= 1)+
  ggtitle("HN Basalt")+
  labs(x=NULL, y=NULL)+
  theme(plot.title = element_text(hjust = 0.5), legend.key.size = unit(1.5, 'cm'),  text=element_text(family="A", size=15))+
  scale_y_continuous(breaks=c(0, .25, .5, .75, 1, 1.25, 1.5, 1.75))+
  coord_cartesian(ylim = c(0, 1.5))
Color_C<-c(expression(C[Litter]),expression(C[SOM]))

C_LNS<-ggplot(SOM_LNS, aes(x=TS, y=C*12*10000/1000/1000, color="CSOM"))+geom_line()+
  geom_line(Litter_All_LNS, mapping= aes(x=TS, y=C/1000, color="CLit"))+
  ggtitle("Low N Sedimentary")+
  labs(x=NULL, y=NULL, color='C Pool')+
  scale_color_manual(values=c("red", "green"),label = Color_C)+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))

C_LNB<-ggplot(SOM_LNB, aes(x=TS, y=C*12*10000/1000/1000, color="CSOM"))+geom_line()+
  geom_line(Litter_All_LNB, mapping= aes(x=TS, y=C/1000, color="CLit"))+
  ggtitle("Low N Basalt")+
  labs(x=NULL, y=NULL, color='C Pool')+
  scale_color_manual(values=c("red", "green"),label = Color_C)+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))


C_HNS<-ggplot(SOM_HNS, aes(x=TS, y=C*12*10000/1000/1000, color="CSOM"))+geom_line()+
  geom_line(Litter_All_HNS, mapping= aes(x=TS, y=C/1000, color="CLit"))+
  ggtitle("High N Sedimentary")+
  labs(x=NULL, y=NULL, color='C Pool')+
  scale_color_manual(values=c("red", "green"),label = Color_C)+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))

C_HNB<-ggplot(SOM_HNB, aes(x=TS, y=C*12*10000/1000/1000, color="CSOM"))+geom_line()+
  geom_line(Litter_All_HNB, mapping= aes(x=TS, y=C/1000, color="CLit"))+
  ggtitle("High N Basalt")+
  labs(x=NULL, y=NULL, color='C Pool')+
  scale_color_manual(values=c("red", "green"),label = Color_C)+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))




# Aggregate

ggarrange(C_LNS, C_HNS, C_LNB, C_HNB, labels=c("A", "B", "C", "D"),
          ncol = 2, nrow = 2, common.legend = TRUE, legend="right", heights =1, widths = 1)%>%
  annotate_figure(left = textGrob("Carbon Pool Size (Mg/ha)", rot = 90, vjust=.45, gp = gpar(cex = 1.3,
                    font.label = list(size = 14, color = "black", face = "bold"))),
                    bottom = textGrob("Time Step (Years)", gp = gpar(cex = 1.3)), top=textGrob("40 BO")) %>%
  ggexport(filename="C_Pool.png", height=1000, width=1000, res=100)

ggarrange(LNS, HNS, LNB, HNB, labels=c("A", "B", "C", "D"),
          ncol = 2, nrow = 2, common.legend = TRUE, legend="right", heights =1, widths = 1)%>%
  annotate_figure(left = textGrob("Nutrient Pool Size", rot = 90, vjust=.45, gp = gpar(cex = 1.3,
                    font.label = list(size = 14, color = "black", face = "bold"))),
                    bottom = textGrob("Time Step (Years)", gp = gpar(cex = 1.3)), top=textGrob("80 BO")) %>%
  ggexport(filename="Nutrient_Pool.png", height=1000, width=1000, res=100)

```

```{r}
rm(list = ls())


source("~/Project_Master/Test_Rep/Code/LN_SED/80_WTH/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/LN_SED/80_WTH/SOM_Mutator.R")
source("~/Project_Master/Test_Rep/Code/HN_SED/80_WTH/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/HN_SED/80_WTH/SOM_Mutator.R")

source("~/Project_Master/Test_Rep/Code/HN_BAS/80_WTH/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/HN_BAS/80_WTH/SOM_Mutator.R")

source("~/Project_Master/Test_Rep/Code/LN_BAS/80_WTH/CEC_Mutator.R")
source("~/Project_Master/Test_Rep/Code/LN_BAS/80_WTH/SOM_Mutator.R")

setwd("~/Project_Master/Test_Rep/Manuscript/Images/Aggregated/80_WTH")

label_color<-c("Ca", "K", "Mg", expression(N[O]), expression(P[O]), expression(S[O]))
# LNS Break

SOM_LNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_SED/80_WTH/Edited Data/SOM.csv")


SOM_LNS<-SOM_LNS %>%group_by(Year, Month)%>% select(-Date) %>% summarise(across(C:P, ~sum(.x, na.rm = TRUE))) %>%
  mutate(Date = make_date(Year, Month)) %>% filter(Month %in% 1)




CEC_All_LNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_SED/80_WTH/Edited Data/CEC_All.csv", header=TRUE)
Litter_All_LNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_SED/80_WTH/Edited Data/Litter_Pool.csv", header=TRUE)

Litter_All_LNS<-Litter_All_LNS %>% filter(Month %in% 1)


CEC_All_LNS$Date<-as.Date(CEC_All_LNS$Date)

CEC_All_LNS[, "year"] <- format(CEC_All_LNS[,"Date"], "%Y")
CEC_All_LNS[, "month"] <- format(CEC_All_LNS[,"Date"], "%m")

CEC_LNS<-CEC_All_LNS %>% group_by(year, month) %>% summarise(across(Ca:Al, ~sum(.x, na.rm=TRUE))) %>% 
  mutate(Date=make_date(year, month))%>% 
  filter(month %in% "01")

CEC_LNS$Date<-as.Date(CEC_LNS$Date)

label_color<-c("C", "Ca", "K","Mg", "N", "P", "S")
label_line<-c("dashed", "solid", "solid", "solid" ,"dashed", "dashed", "dashed")
nut_color<-c("black", "red3", "magenta2", "orange", "green2", "blue", "grey")
order<-c("Ca", "K","Mg", "C","N", "P", "S")

TimeSteps<-seq(1, 513, 1)


SOM_LNS$TS<-TimeSteps
CEC_LNS$TS<-TimeSteps
Litter_All_LNS$TS<-TimeSteps


LNS<-ggplot(CEC_LNS, aes(x=TS, y=CEC_LNS$Ca/6230.915+Litter_All_LNS$Ca/6230.915, color="Ca", linetype="Ca")) + geom_line()+
  geom_line(aes(y=CEC_LNS$Mg/2448.663+Litter_All_LNS$Mg/2448.663, color="Mg", linetype="Mg"))+
  geom_line(aes(y=CEC_LNS$K/1325.840+Litter_All_LNS$K/1325.840, color="K", linetype="K"))+
  geom_line(SOM_LNS, mapping=aes(y=N*14*10/9334.201+Litter_All_LNS$N/9334.201, color="N", linetype="N"))+
  geom_line(SOM_LNS, mapping=aes(y=P*30.974*10/667.97+Litter_All_LNS$P/667.97, color="P", linetype="P"))+
  geom_line(SOM_LNS, mapping=aes(y=S*32.065*10/754+Litter_All_LNS$S/754, color="S", linetype="S"))+
  geom_line(SOM_LNS, mapping=aes(y=(C*12*10+Litter_All_LNS$C)/142975.4, color="C", linetype="C"))+
  scale_linetype_manual(values=label_line, label=label_color)+
  scale_color_manual(values=nut_color, label=label_color)+
  theme_classic2()+
  labs(color  = "Species", linetype="Species")+
  geom_hline(yintercept= 1)+
  ggtitle("LN Sedimentary")+
  labs(x=NULL, y=NULL)+
  theme(plot.title = element_text(hjust = 0.5), legend.key.size = unit(1.5, 'cm'),  text=element_text(family="A", size=15))+
  scale_y_continuous(breaks=c(0, .25, .5, .75, 1, 1.25, 1.5, 1.75))+
  coord_cartesian(ylim = c(0, 1.5))

# HNS Break

SOM_HNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_SED/80_WTH/Edited Data/SOM.csv")


SOM_HNS<-SOM_HNS %>%group_by(Year, Month)%>% select(-Date) %>% summarise(across(C:P, ~sum(.x, na.rm = TRUE))) %>%
  mutate(Date = make_date(Year, Month)) %>% filter(Month %in% 1)




CEC_All_HNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_SED/80_WTH/Edited Data/CEC_All.csv", header=TRUE)
Litter_All_HNS<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_SED/80_WTH/Edited Data/Litter_Pool.csv", header=TRUE)

Litter_All_HNS<-Litter_All_HNS %>% filter(Month %in% 1)


CEC_All_HNS$Date<-as.Date(CEC_All_HNS$Date)

CEC_All_HNS[, "year"] <- format(CEC_All_HNS[,"Date"], "%Y")
CEC_All_HNS[, "month"] <- format(CEC_All_HNS[,"Date"], "%m")

CEC_HNS<-CEC_All_HNS %>% group_by(year, month) %>% summarise(across(Ca:Al, ~sum(.x, na.rm=TRUE))) %>% 
  mutate(Date=make_date(year, month))%>% 
  filter(month %in% "01")

CEC_HNS$Date<-as.Date(CEC_HNS$Date)

SOM_HNS$TS<-TimeSteps
CEC_HNS$TS<-TimeSteps
Litter_All_HNS$TS<-TimeSteps

HNS<-ggplot(CEC_HNS, aes(x=TS, y=CEC_HNS$Ca/269.4037+Litter_All_HNS$Ca/269.4037, color="Ca", linetype="Ca")) + geom_line()+
  geom_line(aes(y=CEC_HNS$Mg/183.0244+Litter_All_HNS$Mg/183.0244, color="Mg", linetype="Mg"))+
  geom_line(aes(y=CEC_HNS$K/437.3307+Litter_All_HNS$K/437.3307, color="K", linetype="K"))+
  geom_line(SOM_HNS, mapping=aes(y=N*14*10/22247.05+Litter_All_HNS$N/22247.05, color="N", linetype="N"))+
  geom_line(SOM_HNS, mapping=aes(y=P*30.974*10/2214+Litter_All_HNS$P/2214, color="P", linetype="P"))+
  geom_line(SOM_HNS, mapping=aes(y=S*32.065*10/1271.698+Litter_All_HNS$S/1271.698, color="S", linetype="S"))+
  geom_line(SOM_HNS, mapping=aes(y=(C*12*10+Litter_All_HNS$C)/418432.9, color="C", linetype="C"))+
  scale_linetype_manual(values=label_line, label=label_color)+
  scale_color_manual(values=nut_color, label=label_color)+
  theme_classic2()+
  labs(color  = "Species", linetype="Species")+
  geom_hline(yintercept= 1)+
  ggtitle("HN Sedimentary")+
  labs(x=NULL, y=NULL)+
  theme(plot.title = element_text(hjust = 0.5), legend.key.size = unit(1.5, 'cm'),  text=element_text(family="A", size=15))+
  scale_y_continuous(breaks=c(0, .25, .5, .75, 1, 1.25, 1.5, 1.75))+
  coord_cartesian(ylim = c(0, 1.5))

# LNB Break

SOM_LNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_BAS/80_WTH/Edited Data/SOM.csv")


SOM_LNB<-SOM_LNB %>%group_by(Year, Month)%>% select(-Date) %>% summarise(across(C:P, ~sum(.x, na.rm = TRUE))) %>%
  mutate(Date = make_date(Year, Month)) %>% filter(Month %in% 1)




CEC_All_LNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_BAS/80_WTH/Edited Data/CEC_All.csv", header=TRUE)
Litter_All_LNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/LN_BAS/80_WTH/Edited Data/Litter_Pool.csv", header=TRUE)

Litter_All_LNB<-Litter_All_LNB %>% filter(Month %in% 1)


CEC_All_LNB$Date<-as.Date(CEC_All_LNB$Date)

CEC_All_LNB[, "year"] <- format(CEC_All_LNB[,"Date"], "%Y")
CEC_All_LNB[, "month"] <- format(CEC_All_LNB[,"Date"], "%m")

CEC_LNB<-CEC_All_LNB %>% group_by(year, month) %>% summarise(across(Ca:Al, ~sum(.x, na.rm=TRUE))) %>% 
  mutate(Date=make_date(year, month))%>% 
  filter(month %in% "01")

CEC_LNB$Date<-as.Date(CEC_LNB$Date)

SOM_LNB$TS<-TimeSteps
CEC_LNB$TS<-TimeSteps
Litter_All_LNB$TS<-TimeSteps

LNB<-ggplot(CEC_LNB, aes(x=TS, y=CEC_LNB$Ca/3364.286+Litter_All_LNB$Ca/3364.286, color="Ca", linetype="Ca")) + geom_line()+
  geom_line(aes(y=CEC_LNB$Mg/3404.168+Litter_All_LNB$Mg/3404.168, color="Mg", linetype="Mg"))+
  geom_line(aes(y=CEC_LNB$K/880.0967+Litter_All_LNB$K/880.0967, color="K", linetype="K"))+
  geom_line(SOM_LNB, mapping=aes(y=N*14*10/9205.251+Litter_All_LNB$N/9205.251, color="N", linetype="N"))+
  geom_line(SOM_LNB, mapping=aes(y=P*30.974*10/643.33+Litter_All_LNB$P/643.33, color="P", linetype="P"))+
  geom_line(SOM_LNB, mapping=aes(y=S*32.065*10/824.22+Litter_All_LNB$S/824.22, color="S", linetype="S"))+
  geom_line(SOM_LNB, mapping=aes(y=(C*12*10+Litter_All_LNB$C)/154973.3, color="C", linetype="C"))+
  scale_linetype_manual(values=label_line, label=label_color)+
  scale_color_manual(values=nut_color, label=label_color)+
  theme_classic2()+
  labs(color  = "Species", linetype="Species")+
  geom_hline(yintercept= 1)+
  ggtitle("LN Basalt")+
  labs(x=NULL, y=NULL)+
  theme(plot.title = element_text(hjust = 0.5), legend.key.size = unit(1.5, 'cm'),  text=element_text(family="A", size=15))+
  scale_y_continuous(breaks=c(0, .25, .5, .75, 1, 1.25, 1.5, 1.75))+
  coord_cartesian(ylim = c(0, 1.5))

# HNB Break 

SOM_HNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_BAS/80_WTH/Edited Data/SOM.csv")


SOM_HNB<-SOM_HNB %>%group_by(Year, Month)%>% select(-Date) %>% summarise(across(C:P, ~sum(.x, na.rm = TRUE))) %>%
  mutate(Date = make_date(Year, Month)) %>% filter(Month %in% 1)




CEC_All_HNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_BAS/80_WTH/Edited Data/CEC_All.csv", header=TRUE)
Litter_All_HNB<-read.csv2("~/Project_Master/Test_Rep/Output/Manuscript/HN_BAS/80_WTH/Edited Data/Litter_Pool.csv", header=TRUE)

Litter_All_HNB<-Litter_All_HNB %>% filter(Month %in% 1)


CEC_All_HNB$Date<-as.Date(CEC_All_HNB$Date)

CEC_All_HNB[, "year"] <- format(CEC_All_HNB[,"Date"], "%Y")
CEC_All_HNB[, "month"] <- format(CEC_All_HNB[,"Date"], "%m")

CEC_HNB<-CEC_All_HNB %>% group_by(year, month) %>% summarise(across(Ca:Al, ~sum(.x, na.rm=TRUE))) %>% 
  mutate(Date=make_date(year, month))%>% 
  filter(month %in% "01")

CEC_HNB$Date<-as.Date(CEC_HNB$Date)

SOM_HNB$TS<-TimeSteps
CEC_HNB$TS<-TimeSteps
Litter_All_HNB$TS<-TimeSteps

HNB<-ggplot(CEC_HNB, aes(x=TS, y=CEC_HNB$Ca/232.34+Litter_All_HNB$Ca/232.34, color="Ca", linetype="Ca")) + geom_line()+
  geom_line(aes(y=CEC_HNB$Mg/267.2+Litter_All_HNB$Mg/267.2, color="Mg", linetype="Mg"))+
  geom_line(aes(y=CEC_HNB$K/163.11+Litter_All_HNB$K/163.11, color="K", linetype="K"))+
  geom_line(SOM_HNB, mapping=aes(y=N*14*10/16757+Litter_All_HNB$N/16757, color="N", linetype="N"))+
  geom_line(SOM_HNB, mapping=aes(y=P*30.974*10/1242.458+Litter_All_HNB$P/1242.458, color="P", linetype="P"))+
  geom_line(SOM_HNB, mapping=aes(y=S*32.065*10/699.88+Litter_All_HNB$S/699.88, color="S", linetype="S"))+
  geom_line(SOM_HNB, mapping=aes(y=(C*12*10+Litter_All_HNB$C)/275094.6, color="C", linetype="C"))+
  scale_linetype_manual(values=label_line, label=label_color)+
  scale_color_manual(values=nut_color, label=label_color)+
  theme_classic2()+
  labs(color  = "Species", linetype="Species")+
  geom_hline(yintercept= 1)+
  ggtitle("HN Basalt")+
  labs(x=NULL, y=NULL)+
  theme(plot.title = element_text(hjust = 0.5), legend.key.size = unit(1.5, 'cm'),  text=element_text(family="A", size=15))+
  scale_y_continuous(breaks=c(0, .25, .5, .75, 1, 1.25, 1.5, 1.75))+
  coord_cartesian(ylim = c(0, 1.5))
Color_C<-c(expression(C[Litter]),expression(C[SOM]))

C_LNS<-ggplot(SOM_LNS, aes(x=TS, y=C*12*10000/1000/1000, color="CSOM"))+geom_line()+
  geom_line(Litter_All_LNS, mapping= aes(x=TS, y=C/1000, color="CLit"))+
  ggtitle("Low N Sedimentary")+
  labs(x=NULL, y=NULL, color='C Pool')+
  scale_color_manual(values=c("red", "green"),label = Color_C)+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))

C_LNB<-ggplot(SOM_LNB, aes(x=TS, y=C*12*10000/1000/1000, color="CSOM"))+geom_line()+
  geom_line(Litter_All_LNB, mapping= aes(x=TS, y=C/1000, color="CLit"))+
  ggtitle("Low N Basalt")+
  labs(x=NULL, y=NULL, color='C Pool')+
  scale_color_manual(values=c("red", "green"),label = Color_C)+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))


C_HNS<-ggplot(SOM_HNS, aes(x=TS, y=C*12*10000/1000/1000, color="CSOM"))+geom_line()+
  geom_line(Litter_All_HNS, mapping= aes(x=TS, y=C/1000, color="CLit"))+
  ggtitle("High N Sedimentary")+
  labs(x=NULL, y=NULL, color='C Pool')+
  scale_color_manual(values=c("red", "green"),label = Color_C)+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))

C_HNB<-ggplot(SOM_HNB, aes(x=TS, y=C*12*10000/1000/1000, color="CSOM"))+geom_line()+
  geom_line(Litter_All_HNB, mapping= aes(x=TS, y=C/1000, color="CLit"))+
  ggtitle("High N Basalt")+
  labs(x=NULL, y=NULL, color='C Pool')+
  scale_color_manual(values=c("red", "green"),label = Color_C)+
  theme_classic()+
  theme(plot.title = element_text(hjust = 0.5))




# Aggregate

ggarrange(C_LNS, C_HNS, C_LNB, C_HNB, labels=c("A", "B", "C", "D"),
          ncol = 2, nrow = 2, common.legend = TRUE, legend="right", heights =1, widths = 1)%>%
  annotate_figure(left = textGrob("Carbon Pool Size (Mg/ha)", rot = 90, vjust=.45, gp = gpar(cex = 1.3,
                    font.label = list(size = 14, color = "black", face = "bold"))),
                    bottom = textGrob("Time Step (Years)", gp = gpar(cex = 1.3)), top=textGrob("40 BO")) %>%
  ggexport(filename="C_Pool.png", height=1000, width=1000, res=100)

ggarrange(LNS, HNS, LNB, HNB, labels=c("A", "B", "C", "D"),
          ncol = 2, nrow = 2, common.legend = TRUE, legend="right", heights =1, widths = 1)%>%
  annotate_figure(left = textGrob("Nutrient Pool Size", rot = 90, vjust=.45, gp = gpar(cex = 1.3,
                    font.label = list(size = 14, color = "black", face = "bold"))),
                    bottom = textGrob("Time Step (Years)", gp = gpar(cex = 1.3)), top=textGrob("80 WTH")) %>%
  ggexport(filename="Nutrient_Pool.png", height=1000, width=1000, res=100)


```





